// Generated by EventMath Compiler v0.1
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== "undefined"
  ? EventMathRuntime
  : require("eventmath-runtime");

// Action: "make requirement"
function makeRequirement(
title, priority
) {
  const made_requirement = new EM.EventMathEvent(
    "made requirement",
    "requirement",
    {
      title: title,
      priority: priority,
      status: "todo",
    }
  );
  window.__evtlog.push(made_requirement); // Append to timeline
  return made_requirement;
}

// Layer: "current sprint"
const current_sprint = new EM.EventMathLayer("current sprint", [
]);

// Event: "t1"
const t1 = new EM.EventMathEvent(
  "t1",
  "requirement",
  {
    title: "User can create account",
    priority: "high",
  }
);

// Event: "t2"
const t2 = new EM.EventMathEvent(
  "t2",
  "requirement",
  {
    title: "User can log in",
    priority: "high",
  }
);

makeRequirement("User can reset password", "medium");
// run layer current sprint
console.log(current_sprint);

// ── Export for use ─────────────────────────────────
module.exports = {
  t1,
  t2,
  current_sprint,
  makeRequirement,
};