// Generated by EventMath Compiler v0.2
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

// Event: "scene 1"
const scene_1 = new EM.EventMathEvent(
  "scene 1",
  "story scene",
  {
    title: "The hero leaves home",
    mood: "hopeful",
  }
);

// Event: "scene 2"
const scene_2 = new EM.EventMathEvent(
  "scene 2",
  "story scene",
  {
    title: "The hero meets a stranger",
    mood: "curious",
  }
);

// Event: "scene 3"
const scene_3 = new EM.EventMathEvent(
  "scene 3",
  "story scene",
  {
    title: "The hero faces a challenge",
    mood: "tense",
  }
);

// Layer: "act 1"
const act_1 = new EM.EventMathLayer("act 1", [
  scene_1,
  scene_2,
  scene_3,
]);

// Timeline: "story"
const story = new EM.EventMathTimeline("story");

story.log.push(...act_1.events);

// run story present
console.log(JSON.stringify(story, null, 2));

// ── Export for use ─────────────────────────────────
module.exports = {
  scene_1,
  scene_2,
  scene_3,
  act_1,
  story,
};