// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let all_done = false;

// Event: "task 1"
const task_1 = new EM.EventMathEvent(
  "task 1",
  "task",
  {
    name: "Design homepage",
    status: "done",
  }
);

// Event: "task 2"
const task_2 = new EM.EventMathEvent(
  "task 2",
  "task",
  {
    name: "Build API",
    status: "done",
  }
);

// Event: "task 3"
const task_3 = new EM.EventMathEvent(
  "task 3",
  "task",
  {
    name: "Write tests",
    status: "done",
  }
);

// Event: "task 4"
const task_4 = new EM.EventMathEvent(
  "task 4",
  "task",
  {
    name: "Deploy",
    status: "done",
  }
);

// Layer: "project tasks"
const project_tasks = new EM.EventMathLayer("project tasks", [
  task_1,
  task_2,
  task_3,
  task_4,
]);

while (!(all_done === true)) {
  all_done = true;
  for (const current_task of project_tasks.events) {
    if (current_task.matter.status !== "done") {
      all_done = false;
    }
  }
}
console.log(task_1.render());
console.log(task_2.render());
console.log(task_3.render());
console.log(task_4.render());

// ── Export for use ─────────────────────────────────
module.exports = {
  task_1,
  task_2,
  task_3,
  task_4,
  project_tasks,
};