// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

// note: These events describe the billing and payment system
// Event: "payment method added"
const payment_method_added = new EM.EventMathEvent(
  "payment method added",
  "billing",
  {
    title: "User can add a credit or debit card",
    priority: "high",
    status: "todo",
  }
);

// Event: "subscription started"
const subscription_started = new EM.EventMathEvent(
  "subscription started",
  "billing",
  {
    title: "User can choose and start a plan",
    priority: "medium",
    status: "todo",
  }
);

// Layer: "billing features"
const billing_features = new EM.EventMathLayer("billing features", [
  payment_method_added,
  subscription_started,
]);


// ── Export for use ─────────────────────────────────
module.exports = {
  payment_method_added,
  subscription_started,
  billing_features,
};