// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

let gap_depth = (deploy_gap.zoomLevel || 1);

// note: Fractal Timeline — zoom reveals the gap between two events
// Event: "code merged"
const code_merged = new EM.EventMathEvent(
  "code merged",
  "development",
  {
    author: "ryan",
    branch: "feature slash payment",
    "files changed": "12",
  }
);

// Event: "deployed to production"
const deployed_to_production = new EM.EventMathEvent(
  "deployed to production",
  "operations",
  {
    version: "2 dot 4 dot 1",
    "servers updated": "3",
    "deploy time": "4 minutes",
  }
);

// Layer: "deployment events"
const deployment_events = new EM.EventMathLayer("deployment events", [
  code_merged,
  deployed_to_production,
]);

// Timeline: "deployment history"
const deployment_history = new EM.EventMathTimeline("deployment history");

deployment_history.log.push(...deployed_to_production.events);

// note: Zoom in — what lives between merge and deploy?
// zoom in on code merged and deployed to production into deploy gap
const deploy_gap = new EM.EventMathTimeline('deploy gap');
deploy_gap.zoomLevel = ((code_merged.zoomLevel || 1) + 1);
const _ctrl_matter_deploy_gap = {
  from: code_merged.id,
  to: deployed_to_production.id,
  zoom_level: deploy_gap.zoomLevel,
  control: true,
  gap_description: 'between code merged and deployed to production'
};
Object.keys(code_merged.matter || {}).forEach(k => { _ctrl_matter_deploy_gap['from_' + k] = code_merged.matter[k]; });
Object.keys(deployed_to_production.matter || {}).forEach(k => { _ctrl_matter_deploy_gap['to_' + k] = deployed_to_production.matter[k]; });
deploy_gap.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_deploy_gap)));

// note: The gap has a zoom level one deeper than the surface
// note: Zoom in again — what lives inside the gap?
// note: This is the fractal principle — the gap contains more gaps
// note: Zoom out — what does the whole deployment look like from above?
// zoom out on timeline deployment history as event deployment summary
const deployment_summary = new EM.EventMathEvent(
  'deployment summary',
  'summary',
  {
    source_type: 'timeline',
    source_name: 'deployment history',
    zoom_level: Math.max(1, (deployment_history.zoomLevel || 1) - 1),
    entry_count: deployment_history.log.length,
    summary: deployment_history.render()
  }
);

// note: The summary is now a single event at a higher level
console.log(deployment_summary.render());
if (!(gap_depth > 1)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "gap depth is greater than 1",
    hint: "This condition was expected to be true.",
  }).render());
}

// ── Export for use ─────────────────────────────────
module.exports = {
  code_merged,
  deployed_to_production,
  deployment_summary,
  deployment_events,
  deployment_history,
  deploy_gap,
};