// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

// note: Opposing Forces — v1.4 fractal governance demo
// note: Every control has an equal and opposite.
// note: Every set of four (A, B, C, C') is governed by a meta-control.
// note: The meta-control has its own equal and opposite.
// note: The structure fractal-repeats at every level.
// note: ── The two primary states ──
// Event: "not knowing"
const not_knowing = new EM.EventMathEvent(
  "not knowing",
  "state",
  {
    name: "not knowing",
    description: "the starting condition of ignorance or incompetence",
    energy: "low",
    direction: "away from mastery",
  }
);

// Event: "knowing"
const knowing = new EM.EventMathEvent(
  "knowing",
  "state",
  {
    name: "knowing",
    description: "the arrived condition of mastery and fluency",
    energy: "high",
    direction: "toward mastery",
  }
);

// note: ── Level 1: zoom in reveals the primary control ──
// zoom in on not knowing and knowing into learning process
const learning_process = new EM.EventMathTimeline('learning process');
learning_process.zoomLevel = ((not_knowing.zoomLevel || 1) + 1);
const _ctrl_matter_learning_process = {
  from: not_knowing.id,
  to: knowing.id,
  zoom_level: learning_process.zoomLevel,
  control: true,
  gap_description: 'between not knowing and knowing'
};
Object.keys(not_knowing.matter || {}).forEach(k => { _ctrl_matter_learning_process['from_' + k] = not_knowing.matter[k]; });
Object.keys(knowing.matter || {}).forEach(k => { _ctrl_matter_learning_process['to_' + k] = knowing.matter[k]; });
learning_process.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_learning_process)));

// note: learning process is what bridges not-knowing to knowing
// note: it is the discipline, repetition, feedback loop that pulls you forward
// note: ── Level 1 opposite: zoom opposite reveals the counter-force ──
// zoom opposite: equal and opposite control of "learning process"
const resistance = (() => {
  const __src = learning_process;
  const __level = (__src && __src.zoomLevel) || 1;
  const __opp = new EM.EventMathTimeline('resistance');
  __opp.zoomLevel = __level;
  __opp.opposite = true;
  __opp.oppositeOf = 'learning process';
  __opp.polarity = -1;
  const __oppMatter = {
    type: 'opposite control',
    opposite_of: 'learning process',
    zoom_level: __level,
    polarity: 'negative',
    description: 'equal and opposite force to ' + 'learning process'
  };
  __opp.append(new EM.TimelineEntry('control', new EM.EventMathEvent('opp_ctrl_' + Date.now(), 'opposite control', __oppMatter)));
  return __opp;
})();

// note: resistance is the equal and opposite of learning process
// note: procrastination, perfectionism, fear — the force pushing back toward not-knowing
// note: without resistance there is no tension — the learning process loses meaning
// note: ── Level 2: zoom meta reveals what governs all four ──
// zoom meta: meta-control governing [not knowing, knowing, learning process, resistance]
const learning_environment = (() => {
  const __governs = [not_knowing, knowing, learning_process, resistance];
  const __maxLevel = Math.max(...__governs.map(s => (s && s.zoomLevel) || 1));
  const __meta = new EM.EventMathTimeline('learning environment');
  __meta.zoomLevel = __maxLevel + 1;
  __meta.meta = true;
  __meta.governs = __governs;
  __meta.governsNames = ['not knowing', 'knowing', 'learning process', 'resistance'];
  const __metaMatter = {
    type: 'meta control',
    governs_count: __governs.length,
    governs: ['not knowing', 'knowing', 'learning process', 'resistance'].join(', '),
    zoom_level: __meta.zoomLevel,
    description: 'meta-control governing the governing controls'
  };
  __meta.append(new EM.TimelineEntry('control', new EM.EventMathEvent('meta_ctrl_' + Date.now(), 'meta control', __metaMatter)));
  return __meta;
})();

// note: learning environment governs all four:
// note: - it determines how hard not-knowing feels
// note: - it determines how far knowing seems
// note: - it determines the strength of the learning process
// note: - it determines the strength of resistance
// note: examples: sleep quality, psychological safety, mentors, urgency, stakes
// note: ── Level 2 opposite: the meta-control has its own equal and opposite ──
// zoom opposite: equal and opposite control of "learning environment"
const environment_collapse = (() => {
  const __src = learning_environment;
  const __level = (__src && __src.zoomLevel) || 1;
  const __opp = new EM.EventMathTimeline('environment collapse');
  __opp.zoomLevel = __level;
  __opp.opposite = true;
  __opp.oppositeOf = 'learning environment';
  __opp.polarity = -1;
  const __oppMatter = {
    type: 'opposite control',
    opposite_of: 'learning environment',
    zoom_level: __level,
    polarity: 'negative',
    description: 'equal and opposite force to ' + 'learning environment'
  };
  __opp.append(new EM.TimelineEntry('control', new EM.EventMathEvent('opp_ctrl_' + Date.now(), 'opposite control', __oppMatter)));
  return __opp;
})();

// note: environment collapse is what destroys even the governing conditions
// note: burnout, isolation, depression, toxic context — the meta-resistance
// note: when environment collapse wins, learning process and resistance both stop mattering
// note: ── Now we can zoom meta again — Level 3 ──
// zoom meta: meta-control governing [learning environment, environment collapse]
const life_conditions = (() => {
  const __governs = [learning_environment, environment_collapse];
  const __maxLevel = Math.max(...__governs.map(s => (s && s.zoomLevel) || 1));
  const __meta = new EM.EventMathTimeline('life conditions');
  __meta.zoomLevel = __maxLevel + 1;
  __meta.meta = true;
  __meta.governs = __governs;
  __meta.governsNames = ['learning environment', 'environment collapse'];
  const __metaMatter = {
    type: 'meta control',
    governs_count: __governs.length,
    governs: ['learning environment', 'environment collapse'].join(', '),
    zoom_level: __meta.zoomLevel,
    description: 'meta-control governing the governing controls'
  };
  __meta.append(new EM.TimelineEntry('control', new EM.EventMathEvent('meta_ctrl_' + Date.now(), 'meta control', __metaMatter)));
  return __meta;
})();

// note: life conditions govern whether learning environment can even exist
// note: examples: financial stability, physical health, relationships, meaning
// note: this is the second-order meta-control — the field that generates the field
// note: ── Show the full governance structure ──
console.log(not_knowing.render());
console.log(knowing.render());
console.log(learning_process.render());
console.log(resistance.render());
console.log(learning_environment.render());
console.log(environment_collapse.render());
console.log(life_conditions.render());

// ── Export for use ─────────────────────────────────
module.exports = {
  not_knowing,
  knowing,
  learning_process,
  resistance,
  learning_environment,
  environment_collapse,
  life_conditions,
};