// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

// use directions from ../prediction/directions.em
const { directions } = require('./../prediction/directions.em.js');
// use lenses from ../prediction/lenses.em
const { lenses } = require('./../prediction/lenses.em.js');
// use quantities from ../prediction/quantities.em
const { quantities } = require('./../prediction/quantities.em.js');

let transition_depth;
let bridge_depth;
let second_layer_depth;
let what_accuracy;
let how_accuracy;
let why_accuracy;
let where_accuracy;

// note: Parallel Universes — computed with zoom and prediction engine
// note: Every gap has structure. Every branch has a bridge.
// Event: "quantum split"
const quantum_split = new EM.EventMathEvent(
  "quantum split",
  "branch point",
  {
    particle: "electron",
    property: "spin",
    "state before": "superposition",
    "branches created": "2",
  }
);

// Event: "spin up realized"
const spin_up_realized = new EM.EventMathEvent(
  "spin up realized",
  "universe alpha",
  {
    result: "up",
    probability: "0.5",
    universe: "alpha",
  }
);

// Event: "spin down realized"
const spin_down_realized = new EM.EventMathEvent(
  "spin down realized",
  "universe beta",
  {
    result: "down",
    probability: "0.5",
    universe: "beta",
  }
);

// Layer: "branch point"
const branch_point = new EM.EventMathLayer("branch point", [
  quantum_split,
]);

// Layer: "alpha branch"
const alpha_branch = new EM.EventMathLayer("alpha branch", [
  spin_up_realized,
]);

// Layer: "beta branch"
const beta_branch = new EM.EventMathLayer("beta branch", [
  spin_down_realized,
]);

// Timeline: "universe alpha"
const universe_alpha = new EM.EventMathTimeline("universe alpha");

universe_alpha.log.push(...alpha_branch.events);

// Timeline: "universe beta"
const universe_beta = new EM.EventMathTimeline("universe beta");

universe_beta.log.push(...beta_branch.events);

// note: ZOOM 1 — between measurement and outcome lives a timeline
// zoom in on quantum split and spin up realized into quantum transition
const quantum_transition = new EM.EventMathTimeline('quantum transition');
quantum_transition.zoomLevel = ((quantum_split.zoomLevel || 1) + 1);
const _ctrl_matter_quantum_transition = {
  from: quantum_split.id,
  to: spin_up_realized.id,
  zoom_level: quantum_transition.zoomLevel,
  control: true,
  gap_description: 'between quantum split and spin up realized'
};
Object.keys(quantum_split.matter || {}).forEach(k => { _ctrl_matter_quantum_transition['from_' + k] = quantum_split.matter[k]; });
Object.keys(spin_up_realized.matter || {}).forEach(k => { _ctrl_matter_quantum_transition['to_' + k] = spin_up_realized.matter[k]; });
quantum_transition.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_quantum_transition)));

transition_depth = (quantum_transition.zoomLevel || 1);
if (!(transition_depth > 1)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "transition depth is greater than 1",
    hint: "This condition was expected to be true.",
  }).render());
}
// note: ZOOM 2 — between two parallel universes lives a timeline
// zoom in on universe alpha and universe beta into decoherence bridge
const decoherence_bridge = new EM.EventMathTimeline('decoherence bridge');
decoherence_bridge.zoomLevel = ((universe_alpha.zoomLevel || 1) + 1);
const _ctrl_matter_decoherence_bridge = {
  from: universe_alpha.name,
  to: universe_beta.name,
  zoom_level: decoherence_bridge.zoomLevel,
  control: true,
  gap_description: 'between universe alpha and universe beta'
};
decoherence_bridge.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_decoherence_bridge)));

bridge_depth = (decoherence_bridge.zoomLevel || 1);
if (!(bridge_depth > 1)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "bridge depth is greater than 1",
    hint: "This condition was expected to be true.",
  }).render());
}
// note: ZOOM 3 — inside the bridge lives another timeline
// zoom in on universe alpha and decoherence bridge into second layer bridge
const second_layer_bridge = new EM.EventMathTimeline('second layer bridge');
second_layer_bridge.zoomLevel = ((universe_alpha.zoomLevel || 1) + 1);
const _ctrl_matter_second_layer_bridge = {
  from: universe_alpha.name,
  to: decoherence_bridge.name,
  zoom_level: second_layer_bridge.zoomLevel,
  control: true,
  gap_description: 'between universe alpha and decoherence bridge'
};
second_layer_bridge.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_second_layer_bridge)));

second_layer_depth = (second_layer_bridge.zoomLevel || 1);
if (!(second_layer_depth > 1)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "second layer depth is greater than 1",
    hint: "This condition was expected to be true.",
  }).render());
}
// note: Three levels deep — the fractal principle holds
// zoom out on timeline universe alpha as event alpha summary
const alpha_summary = new EM.EventMathEvent(
  'alpha summary',
  'summary',
  {
    source_type: 'timeline',
    source_name: 'universe alpha',
    zoom_level: Math.max(1, (universe_alpha.zoomLevel || 1) - 1),
    entry_count: universe_alpha.log.length,
    summary: universe_alpha.render()
  }
);

// zoom out on timeline universe beta as event beta summary
const beta_summary = new EM.EventMathEvent(
  'beta summary',
  'summary',
  {
    source_type: 'timeline',
    source_name: 'universe beta',
    zoom_level: Math.max(1, (universe_beta.zoomLevel || 1) - 1),
    entry_count: universe_beta.log.length,
    summary: universe_beta.render()
  }
);

// predict: "structure of reality" → reality predictions
const reality_predictions = new EM.EventMathLayer('reality predictions', []);
directions.events.forEach(_dir => {
  lenses.events.forEach(_lens => {
    quantities.events.forEach(_qty => {
      reality_predictions.events.push(new EM.EventMathEvent(
        'prediction_' + Date.now() + '_' + Math.random().toString(36).slice(2),
        'prediction',
        {
          subject: 'structure of reality',
          direction: _dir.matter ? _dir.matter.name : String(_dir.id),
          lens: _lens.matter ? _lens.matter.name : String(_lens.id),
          quantity: _qty.matter ? _qty.matter.name : String(_qty.id),
          predicted_state: (_dir.matter ? _dir.matter.name : '') + ' change through ' + (_lens.matter ? _lens.matter.name : '') + ' lens affecting ' + (_qty.matter ? _qty.matter.name : ''),
          confidence: 0.5,
          resolved: false,
          correct: null
        }
      ));
    });
  });
});

// resolve: reality predictions
reality_predictions.events = reality_predictions.events.map(_p => {
  if ((_p.matter.direction === "direct") && (_p.matter.lens === "what")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: reality predictions
reality_predictions.events = reality_predictions.events.map(_p => {
  if ((_p.matter.direction === "indirect opposite") && (_p.matter.lens === "how")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: false }));
  }
  return _p;
});
// resolve: reality predictions
reality_predictions.events = reality_predictions.events.map(_p => {
  if ((_p.matter.direction === "keep same") && (_p.matter.lens === "why")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: reality predictions
reality_predictions.events = reality_predictions.events.map(_p => {
  if ((_p.matter.direction === "indirect other") && (_p.matter.lens === "where")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
what_accuracy = (function() {
  const _resolved = reality_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "what"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
how_accuracy = (function() {
  const _resolved = reality_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "how"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
why_accuracy = (function() {
  const _resolved = reality_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "why"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
where_accuracy = (function() {
  const _resolved = reality_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "where"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
if (!(what_accuracy === 1)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "what accuracy is 1",
    hint: "This condition was expected to be true.",
  }).render());
}
if (!(how_accuracy === 0)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "how accuracy is 0",
    hint: "This condition was expected to be true.",
  }).render());
}
console.log(universe_alpha.renderSection('past'));
console.log(universe_alpha.renderSection('present'));
console.log(universe_beta.renderSection('present'));
console.log(quantum_transition.renderSection('present'));
console.log(decoherence_bridge.renderSection('present'));
console.log(second_layer_bridge.renderSection('present'));
console.log(alpha_summary.render());
console.log(beta_summary.render());

// ── Export for use ─────────────────────────────────
module.exports = {
  quantum_split,
  spin_up_realized,
  spin_down_realized,
  alpha_summary,
  beta_summary,
  branch_point,
  alpha_branch,
  beta_branch,
  reality_predictions,
  universe_alpha,
  universe_beta,
  quantum_transition,
  decoherence_bridge,
  second_layer_bridge,
};