// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

// note: These events describe a software development sprint
// Event: "user can log in"
const user_can_log_in = new EM.EventMathEvent(
  "user can log in",
  "feature",
  {
    title: "User can authenticate with email and password",
    priority: "high",
    status: "todo",
  }
);

// Event: "user can sign up"
const user_can_sign_up = new EM.EventMathEvent(
  "user can sign up",
  "feature",
  {
    title: "User can create a new account",
    priority: "high",
    status: "todo",
  }
);

// Event: "user can reset password"
const user_can_reset_password = new EM.EventMathEvent(
  "user can reset password",
  "feature",
  {
    title: "User can recover access to their account",
    priority: "medium",
    status: "todo",
  }
);

// Layer: "auth features"
const auth_features = new EM.EventMathLayer("auth features", [
  user_can_log_in,
  user_can_sign_up,
  user_can_reset_password,
]);


// ── Export for use ─────────────────────────────────
module.exports = {
  user_can_log_in,
  user_can_sign_up,
  user_can_reset_password,
  auth_features,
};