// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

// note: EventMath Torus — v1.5
// note: The shape that emerges when you map all the controls.
// note: Not a sphere. A torus. The nucleus switches — it is the hole.
// note: Stacking squares, not polygons. Fibonacci emerges from the count.
// note: ── The two primary states ──
// Event: "not knowing"
const not_knowing = new EM.EventMathEvent(
  "not knowing",
  "state",
  {
    description: "the starting condition before mastery",
    energy: "low",
    direction: "away",
  }
);

// Event: "knowing"
const knowing = new EM.EventMathEvent(
  "knowing",
  "state",
  {
    description: "the arrived condition of mastery and fluency",
    energy: "high",
    direction: "toward",
  }
);

// note: ── Build the control structure ──
// zoom in on not knowing and knowing into learning bridge
const learning_bridge = new EM.EventMathTimeline('learning bridge');
learning_bridge.zoomLevel = ((not_knowing.zoomLevel || 1) + 1);
const _ctrl_matter_learning_bridge = {
  from: not_knowing.id,
  to: knowing.id,
  zoom_level: learning_bridge.zoomLevel,
  control: true,
  gap_description: 'between not knowing and knowing'
};
Object.keys(not_knowing.matter || {}).forEach(k => { _ctrl_matter_learning_bridge['from_' + k] = not_knowing.matter[k]; });
Object.keys(knowing.matter || {}).forEach(k => { _ctrl_matter_learning_bridge['to_' + k] = knowing.matter[k]; });
learning_bridge.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_learning_bridge)));

// zoom opposite: equal and opposite control of "learning bridge"
const resistance_bridge = (() => {
  const __src = learning_bridge;
  const __level = (__src && __src.zoomLevel) || 1;
  const __opp = new EM.EventMathTimeline('resistance bridge');
  __opp.zoomLevel = __level;
  __opp.opposite = true;
  __opp.oppositeOf = 'learning bridge';
  __opp.polarity = -1;
  const __oppMatter = {
    type: 'opposite control',
    opposite_of: 'learning bridge',
    zoom_level: __level,
    polarity: 'negative',
    description: 'equal and opposite force to ' + 'learning bridge'
  };
  __opp.append(new EM.TimelineEntry('control', new EM.EventMathEvent('opp_ctrl_' + Date.now(), 'opposite control', __oppMatter)));
  return __opp;
})();

// zoom meta: meta-control governing [not knowing, knowing, learning bridge, resistance bridge]
const learning_field = (() => {
  const __governs = [not_knowing, knowing, learning_bridge, resistance_bridge];
  const __maxLevel = Math.max(...__governs.map(s => (s && s.zoomLevel) || 1));
  const __meta = new EM.EventMathTimeline('learning field');
  __meta.zoomLevel = __maxLevel + 1;
  __meta.meta = true;
  __meta.governs = __governs;
  __meta.governsNames = ['not knowing', 'knowing', 'learning bridge', 'resistance bridge'];
  const __metaMatter = {
    type: 'meta control',
    governs_count: __governs.length,
    governs: ['not knowing', 'knowing', 'learning bridge', 'resistance bridge'].join(', '),
    zoom_level: __meta.zoomLevel,
    description: 'meta-control governing the governing controls'
  };
  __meta.append(new EM.TimelineEntry('control', new EM.EventMathEvent('meta_ctrl_' + Date.now(), 'meta control', __metaMatter)));
  return __meta;
})();

// note: learning field is now at zoom level 3
// note: it governs: not knowing, knowing, learning bridge, resistance bridge
// note: ── Spin the field into a torus ──
// spin learning field into knowledge torus
const knowledge_torus = new EM.EventMathTorus('knowledge torus');
knowledge_torus.spinFrom(learning_field);

// note: knowledge torus is the shape that emerges
// note: the nucleus is the switch: present when total+1 is Fibonacci
// note: ── Vibrate outward: 8 rings ──
// vibrate knowledge torus across 8 rings
knowledge_torus.expand(8);

// note: Ring 1: 4 pts → outer: 4 +nucleus = 5 Fibonacci ✓
// note: Ring 2: 4 pts → outer: 8 +nucleus = 9
// note: Ring 3: 4 pts → outer: 12 +nucleus = 13 Fibonacci ✓
// note: Ring 4: 4 pts → outer: 16 +nucleus = 17
// note: Ring 5: 4 pts → outer: 20 +nucleus = 21 Fibonacci ✓
// note: Ring 6: 4 pts → outer: 24 +nucleus = 25
// note: Ring 7: 4 pts → outer: 28 +nucleus = 29
// note: Ring 8: 4 pts → outer: 32 +nucleus = 33
// note: ── Cross-level resonance ──
// note: learning bridge and resistance bridge vibrate at the same frequency
// note: they are at different zoom levels but they resonate — they know each other
// resonate learning bridge and resistance bridge
if (learning_bridge && typeof learning_bridge.addResonance === 'function') learning_bridge.addResonance('resistance bridge');
if (resistance_bridge && typeof resistance_bridge.addResonance === 'function') resistance_bridge.addResonance('learning bridge');

// note: ── Complete the cycle ──
// note: the 33rd outer point + nucleus = 34 — the next Fibonacci is 34
// note: cycle marks the return to 1, one level up
// cycle knowledge torus — mark the completion event
knowledge_torus.complete();

// note: ── Output ──
{ const __sv = knowledge_torus; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('knowledge torus:', __sv); } }

// ── Export for use ─────────────────────────────────
module.exports = {
  not_knowing,
  knowing,
  learning_bridge,
  resistance_bridge,
  learning_field,
};