// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let contact_text = "Reach alice@example.com or bob@corp.org for help";
let raw_phone = "(555) 867-5309";
let page_html = "<h1>Welcome to EventMath</h1><h2>Getting Started</h2><h3>Examples</h3>";
let sample = "OrderTotal is Amount plus Tax";
let colors = "#FF5733 and #1ABC9C and #3498DB";

// note: v2.18 — new pattern atoms, replace, zoom out from, zoom expand
// note: ── Email Replace Example ──────────────────────────────────────────
// pattern: email address
const email_address = new RegExp("(?<user>[a-zA-Z0-9._%-+]+)(?<at>@)(?<domain>[a-zA-Z0-9.-]+)(?<extension>\\.[a-zA-Z]{2,})", 'gm');
const found_emails = [...contact_text.matchAll(email_address)].map(function(m) { return m.groups; });
const first_email = (function() { var _r = new RegExp(email_address.source, 'm'); var _m = _r.exec(contact_text); return _m ? _m.groups : null; }());
const redacted_contacts = contact_text.replace(email_address, "$<user> [at] $<domain>$<extension>");
{ const __sv = redacted_contacts; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('redacted contacts:', __sv); } }
{ const __sv = first_email; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('first email:', __sv); } }
// note: ── Phone Number Reformat ──────────────────────────────────────────
// pattern: us phone
const us_phone = new RegExp("(?<area>\\([0-9]{3,3}\\))(?<spacer>(?:\\s)?)(?<prefix>[0-9]{3,3})(?<dash>\\-)(?<number>[0-9]{4,4})", 'gm');
const formatted_phone = raw_phone.replace(us_phone, "$<area> $<prefix>$<dash>$<number>");
{ const __sv = formatted_phone; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('formatted phone:', __sv); } }
// note: ── Heading Extraction and Replace ─────────────────────────────────
// pattern: html heading
const html_heading = new RegExp("(?<open_tag><h[1-6][^>]*>)(?<content>[\\s\\S]*?)(?<close_tag></h[1-6]>)", 'gm');
const headings = [...page_html.matchAll(html_heading)].map(function(m) { return m.groups; });
const stripped_headings = page_html.replace(html_heading, "<span>$<content></span>");
{ const __sv = headings; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('headings:', __sv); } }
{ const __sv = stripped_headings; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('stripped headings:', __sv); } }
// note: ── Uppercase and Lowercase Patterns ────────────────────────────────
// pattern: identifier
const identifier = new RegExp("(?<start>[A-Z])(?<rest>[a-z0-9_]+)", 'gm');
const first_word = (function() { var _r = new RegExp(identifier.source, 'm'); var _m = _r.exec(sample); return _m ? _m.groups : null; }());
{ const __sv = first_word; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('first word:', __sv); } }
// note: ── Hex Color Pattern ───────────────────────────────────────────────
// pattern: hex color
const hex_color = new RegExp("(?<hash>\\#)(?<red>[0-9a-fA-F]{2,2})(?<green>[0-9a-fA-F]{2,2})(?<blue>[0-9a-fA-F]{2,2})", 'gm');
const found_colors = [...colors.matchAll(hex_color)].map(function(m) { return m.groups; });
{ const __sv = found_colors; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('found colors:', __sv); } }
// note: ── Zoom Out From Example ───────────────────────────────────────────
// Event: "no income"
const no_income = new EM.EventMathEvent(
  "no income",
  "state",
  {
    energy: "low",
    signal: "absent",
  }
);

// Event: "consistent income"
const consistent_income = new EM.EventMathEvent(
  "consistent income",
  "state",
  {
    energy: "high",
    signal: "present",
  }
);

// zoom in on no income and consistent income into revenue bridge
const revenue_bridge = new EM.EventMathTimeline('revenue bridge');
revenue_bridge.zoomLevel = ((no_income.zoomLevel || 1) + 1);
const _ctrl_matter_revenue_bridge = {
  from: no_income.id,
  to: consistent_income.id,
  zoom_level: revenue_bridge.zoomLevel,
  control: true,
  gap_description: 'between no income and consistent income'
};
Object.keys(no_income.matter || {}).forEach(k => { _ctrl_matter_revenue_bridge['from_' + k] = no_income.matter[k]; });
Object.keys(consistent_income.matter || {}).forEach(k => { _ctrl_matter_revenue_bridge['to_' + k] = consistent_income.matter[k]; });
revenue_bridge.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_revenue_bridge)));

// zoom out from revenue bridge into bridge context — reverse a zoom, reconstruct parent context
const bridge_context = (() => {
  const __src = revenue_bridge;
  const __srcLevel = (__src && __src.zoomLevel) || 1;
  const __ctrl = (__src && (__src.log || __src.events) && (__src.log || __src.events)[0]);
  const __ctrlMatter = __ctrl ? (__ctrl.matter || __ctrl.event && __ctrl.event.matter || {}) : {};
  const __ctx = {
    source: 'revenue bridge',
    zoom_level: Math.max(1, __srcLevel - 1),
    parent_level: Math.max(0, __srcLevel - 2),
    from: __ctrlMatter.from || null,
    to: __ctrlMatter.to || null,
    gap_description: __ctrlMatter.gap_description || null,
    constituents: Object.fromEntries(
      Object.entries(__ctrlMatter).filter(([k]) => k.startsWith('from_') || k.startsWith('to_'))
    ),
    render: function() {
      return 'context of ' + 'revenue bridge' + ': from=' + this.from + ', to=' + this.to + ', level=' + this.zoom_level;
    }
  };
  return __ctx;
})();

{ const __sv = bridge_context; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('bridge context:', __sv); } }
// note: ── Zoom Expand Example ─────────────────────────────────────────────
// Event: "market suppression"
const market_suppression = new EM.EventMathEvent(
  "market suppression",
  "state",
  {
    energy: "against",
    signal: "suppressed",
    force: "external",
  }
);

// zoom expand on market suppression into suppression field — panoramic expansion from one node
const suppression_field = (() => {
  const __src = market_suppression;
  const __srcLevel = (__src && __src.zoomLevel) || 1;
  const __matter = (__src && __src.matter) || {};
  const __field = {
    source: 'market suppression',
    source_type: 'event',
    zoom_level: __srcLevel + 1,
    matter: __matter,
    surface_area: Object.keys(__matter).length,
    connections: Object.entries(__matter).map(function(e) { return { key: e[0], value: e[1] }; }),
    polarity: (__matter.energy === 'against' || __matter.energy === 'low' || __matter.signal === 'suppressed') ? 'negative' : 'positive',
    expansion_axis: 'market suppression ↔ field',
    render: function() {
      return 'expanded field of ' + 'market suppression' + ' (' + this.surface_area + ' connections, level ' + this.zoom_level + ')';
    }
  };
  return __field;
})();

{ const __sv = suppression_field; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('suppression field:', __sv); } }
// note: ── Zoom Expand on Layer ────────────────────────────────────────────
// Layer: "market states"
const market_states = new EM.EventMathLayer("market states", [
  no_income,
  market_suppression,
]);

// zoom expand on market states into market field — panoramic expansion from one node
const market_field = (() => {
  const __src = market_states;
  const __srcLevel = (__src && __src.zoomLevel) || 1;
  const __matter = (__src && __src.matter) || {};
  const __allMatter = {};
  if (__src.events) __src.events.forEach(function(ev) { Object.assign(__allMatter, ev.matter || {}); });
  Object.assign(__allMatter, __matter);
  const __field = {
    source: 'market states',
    source_type: 'layer',
    zoom_level: __srcLevel + 1,
    matter: __allMatter,
    surface_area: Object.keys(__allMatter).length,
    connections: Object.entries(__allMatter).map(function(e) { return { key: e[0], value: e[1] }; }),
    polarity: (__matter.energy === 'against' || __matter.energy === 'low' || __matter.signal === 'suppressed') ? 'negative' : 'positive',
    expansion_axis: 'market states ↔ field',
    render: function() {
      return 'expanded field of ' + 'market states' + ' (' + this.surface_area + ' connections, level ' + this.zoom_level + ')';
    }
  };
  return __field;
})();

{ const __sv = market_field; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('market field:', __sv); } }

// ── Export for use ─────────────────────────────────
module.exports = {
  no_income,
  consistent_income,
  market_suppression,
  market_states,
  revenue_bridge,
};