// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let climate_debate = null;
let news_coverage = null;
let tech_industry = null;
let scientific_view = null;
let bias_weight = 0.3;
let conservative_view = null;
let skeptical_view = null;
let filter_strength = 0.7;
let optimistic_view = null;
let optimism_bias = 0.8;
let climate_alternatives = null;
let growth_scenarios = null;
let political_outcomes = null;
let green_revolution = null;
let emission_reduction = 0.4;
let economic_impact = "positive for renewables";
let policy_stalemate = null;
let delay_years = 3;
let impact = "continued uncertainty";
let tech_bubble = null;
let crash_severity = "moderate";
let affected_sectors = "tech stocks";
let global_cooperation = null;
let treaty_year = 2030;
let expected_outcome = "binding emissions targets";
let total_scenarios = 4;
let primary_perspective = "scientific_view";
let most_likely = "green_revolution";
let risk_factors = "economic uncertainty and political division";
let climate_awareness = undefined;

const __emStory = require('../runtime/eventmath-story-runtime.js');
Object.assign(EM, __emStory);

// story: climate_debate
climate_debate = new EM.EventMathStory('climate_debate', 'twitter', "\"climate change\"");
climate_debate.scan().then(function(events) { climate_events = events; }).catch(function(err) { console.error('Story scan failed:', err); });

// story: news_coverage
news_coverage = new EM.EventMathStory('news_coverage', 'news', "\"climate policy\"");
news_coverage.scan().then(function(events) { news_events = events; }).catch(function(err) { console.error('Story scan failed:', err); });

// story: tech_industry
tech_industry = new EM.EventMathStory('tech_industry', 'rss', "\"AI regulation\"");
tech_industry.scan().then(function(events) { tech_events = events; }).catch(function(err) { console.error('Story scan failed:', err); });

// narrative: scientific_view
(function() {
  const _narrative = new EM.EventMathNarrative('scientific');
  scientific_view = climate_debate ? _narrative.view(climate_debate) : [];
})();
scientific_view._type = 'narrative';

// narrative: conservative_view
(function() {
  const _narrative = new EM.EventMathNarrative('conservative');
  conservative_view = climate_debate ? _narrative.view(climate_debate) : [];
})();
conservative_view._type = 'narrative';

// narrative: skeptical_view
(function() {
  const _narrative = new EM.EventMathNarrative('skeptical');
  skeptical_view = news_coverage ? _narrative.view(news_coverage) : [];
})();
skeptical_view._type = 'narrative';

// narrative: optimistic_view
(function() {
  const _narrative = new EM.EventMathNarrative('optimistic');
  optimistic_view = tech_industry ? _narrative.view(tech_industry) : [];
})();
optimistic_view._type = 'narrative';

// scope: climate_risk
climate_alternatives = EM.EventMathScope.analyze('climate_risk', ["economic", "environmental", "political"]);

// scope: tech_growth
growth_scenarios = EM.EventMathScope.analyze('tech_growth', ["regulation", "innovation", "market"]);

// scope: political_landscape
political_outcomes = EM.EventMathScope.analyze('political_landscape', ["domestic", "foreign", "economic"]);

// scenario: green_revolution when carbon tax passes
green_revolution = { name: 'green_revolution', condition: 'carbon tax passes', probability: 'high', _type: 'scenario' };

// scenario: policy_stalemate when no agreement reached
policy_stalemate = { name: 'policy_stalemate', condition: 'no agreement reached', probability: 'medium', _type: 'scenario' };

// scenario: tech_bubble when AI investment overheats
tech_bubble = { name: 'tech_bubble', condition: 'AI investment overheats', probability: 'low', _type: 'scenario' };

// scenario: global_cooperation when major powers agree
global_cooperation = { name: 'global_cooperation', condition: 'major powers agree', probability: 'low', _type: 'scenario' };

climate_awareness = "high";