// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let here = null;
let total = null;

// note: v2.29 — The Stigmergy Layer (relocating memory)
// note: 
// note: The idea: an animal is a near-stateless agent. It holds no memory of its
// note: own. Its memory lives in a shared analog medium — the physical world — as
// note: trails. When the animal is gone, the trail remains: the memory never
// note: disappears, it relocates. Computation is the loop between sense and trail.
// note: This is why animals can code: the program is the rule, the state is the ground.
// note: The shared analog memory — the physical world.
// world: meadow — a shared analog memory (the physical world)
const meadow = new EM.EventMathWorld('meadow');

// note: Two stateless agents. Neither carries anything between steps.
// animal: ant — a stateless agent (holds no memory of its own)
const ant = new EM.EventMathAnimal('ant');

// animal: beetle — a stateless agent (holds no memory of its own)
const beetle = new EM.EventMathAnimal('beetle');

// note: The ant arrives, senses the world, then lays a trail. It keeps nothing.
// sense: "food" in meadow into here
here = meadow.sense('food');

// trail: lay "food" in meadow by 1
meadow.lay('food', 1);

// note: The beetle arrives later. It shares NO internal state with the ant —
// note: only the meadow. It reads what the ant left, and adds to it.
// sense: "food" in meadow into here
here = meadow.sense('food');

// trail: lay "food" in meadow by 1
meadow.lay('food', 1);

// note: The count lives in the meadow, not in any animal. Read it back from the world.
// sense: "food" in meadow into total
total = meadow.sense('food');

{ const __sv = meadow; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('meadow:', __sv); } }
// note: Analog decay. Memory weakens but never disappears — strength relocates
// note: onto the strongest paths, so the colony remembers where the food was.
// fade: meadow by 1 (analog decay — never disappears)
meadow.fade(1);

{ const __sv = meadow; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('meadow:', __sv); } }
// note: Even after both animals are gone, the meadow still holds the memory.
{ const __sv = meadow; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('meadow:', __sv); } }