// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let s = null;
let l = null;

// note: v2.32 — colony + march (consensus no single forager chose)
// note: 
// note: One forager is a rule. A colony is a population of that rule, sharing one
// note: world, with evaporation between rounds. Run it and watch a decision emerge:
// note: the colony converges on one route through positive feedback and decay —
// note: reinforcement piles onto the stronger trail, evaporation erases the rest.
// note: No ant decides. The colony computes it, and the answer lives in the world.
// world: paths — a shared analog memory (the physical world)
const paths = new EM.EventMathWorld('paths');

// note: Two routes to the food. A scout marked the quicker one slightly stronger.
// trail: lay "short" in paths by 2 (laid by hand)
paths.lay('short', 2, 'hand');

// trail: lay "long" in paths by 1 (laid by hand)
paths.lay('long', 1, 'hand');

// note: Ten stateless ants. Each follows the stronger scent and reinforces it.
// note: Between rounds the world evaporates by 4 — weak trails cannot survive.
// colony: "ants" — 10 stateless foragers on paths, evaporation 4/round
// No forager holds the outcome; the colony computes it in the world.
function __forage_ants() {
  // sense: "short" in paths into s
  s = paths.sense('short');
  
  // sense: "long" in paths into l
  l = paths.sense('long');
  
  if (s > l) {
    // trail: lay "short" in paths by 6 (laid by ants)
    paths.lay('short', 6, 'ants');
    
  }
  if (l > s) {
    // trail: lay "long" in paths by 3 (laid by ants)
    paths.lay('long', 3, 'ants');
    
  }
}

// note: March the colony for three rounds.
// march: ants — 3 round(s) of 10 forager(s), then evaporation
for (let __r = 0; __r < 3; __r++) {
  for (let __a = 0; __a < 10; __a++) { __forage_ants(); }
  paths.fade(4);
}

// note: The world now holds the colony's decision.
{ const __sv = paths; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('paths:', __sv); } }
// note: Ask why — the colony's choice explains itself, down to who laid what.
// why: "short" in paths
console.log(paths.why('short').render());

// why: "long" in paths
console.log(paths.why('long').render());
