// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let strength = null;
let report = null;

// note: v2.31 — why over trails (the relocated memory explains itself)
// note: 
// note: The bet of this language: the system should be able to explain itself back
// note: to you. v2.29–2.30 moved memory out of the agent and into the world. Now
// note: the world can answer "why is this trail strong?" — tracing the strength
// note: back to who laid what, and what decay wore away. The ground keeps the
// note: receipts, so the memory is not just stored, it is accountable.
// world: meadow — a shared analog memory (the physical world)
const meadow = new EM.EventMathWorld('meadow');

// note: A passing animal found food once and left the first mark — laid by hand.
// trail: lay "food" in meadow by 1 (laid by hand)
meadow.lay('food', 1, 'hand');

// note: The stateless scout reinforces the food trail on every visit.
// forage: "scout" on meadow — a stateless rule.
// It holds no memory of its own; its state lives in the world.
function __forage_scout() {
  // sense: "food" in meadow into strength
  strength = meadow.sense('food');
  
  if (strength > 0) {
    // trail: lay "food" in meadow by 2 (laid by scout)
    meadow.lay('food', 2, 'scout');
    
  }
}

// step: scout — 4 time(s)
for (let __s = 0; __s < 4; __s++) { __forage_scout(); }

// note: Ask the meadow to explain itself. No animal holds this answer — the world does.
// why: "food" in meadow
console.log(meadow.why('food').render());

// note: Night falls; weak trails evaporate.
// fade: meadow by 5 (analog decay — never disappears)
meadow.fade(5);

// note: Ask again — now the trace also accounts for the decay.
// why: "food" in meadow
console.log(meadow.why('food').render());

// note: You can also capture the trace and show it later.
// why: "food" in meadow into report
report = meadow.why('food');

{ const __sv = report; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('report:', __sv); } }