// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let strength = null;

// note: v2.30 — The forage block (a stateless rule) + step
// note: 
// note: A forager is the rule, not the memory. It senses the world, lays a trail,
// note: and keeps nothing. Run the SAME stateless forager many times and watch the
// note: memory accumulate — entirely in the world. That is the program: the rule is
// note: the forager, the state is the ground. This is how a colony computes a path
// note: no single animal holds. Animals can code.
// note: The shared analog memory.
// world: meadow — a shared analog memory (the physical world)
const meadow = new EM.EventMathWorld('meadow');

// note: One animal stumbled on food once and left the first mark.
// trail: lay "food" in meadow by 1
meadow.lay('food', 1);

// note: The scout is stateless. Inside forage the world is implicit — it forages
// note: on the meadow, so it never names it again. It senses, and where it smells
// note: food it reinforces the trail. It holds no memory of its own.
// forage: "scout" on meadow — a stateless rule.
// It holds no memory of its own; its state lives in the world.
function __forage_scout() {
  // sense: "food" in meadow into strength
  strength = meadow.sense('food');
  
  if (strength > 0) {
    // trail: lay "food" in meadow by 2
    meadow.lay('food', 2);
    
  }
}

// note: Run the stateless scout four times. Nothing persists in the scout —
// note: yet the food trail grows, because the memory lives in the meadow.
// step: scout — 4 time(s)
for (let __s = 0; __s < 4; __s++) { __forage_scout(); }

{ const __sv = meadow; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('meadow:', __sv); } }
// note: Night falls. Weak trails evaporate; the strong food memory survives —
// note: it relocated onto the path worth keeping.
// fade: meadow by 5 (analog decay — never disappears)
meadow.fade(5);

{ const __sv = meadow; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('meadow:', __sv); } }