// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

// use directions from ../prediction/directions.em
const { directions } = require('./../prediction/directions.em.js');
// use lenses from ../prediction/lenses.em
const { lenses } = require('./../prediction/lenses.em.js');
// use quantities from ../prediction/quantities.em
const { quantities } = require('./../prediction/quantities.em.js');

let direct_accuracy;
let indirect_other_accuracy;
let indirect_opposite_accuracy;
let keep_same_accuracy;
let who_accuracy;
let what_accuracy;
let timing_accuracy;
let why_accuracy;

// note: Web Development Promotion — Prediction Model
// note: Finding the innovative approach nobody else is using
// Event: "google search ads"
const google_search_ads = new EM.EventMathEvent(
  "google search ads",
  "promotion channel",
  {
    name: "google search ads",
    direction: "direct",
    lens: "where",
    cost: "high",
    competition: "very high",
    saturation: "yes",
  }
);

// Event: "portfolio website"
const portfolio_website = new EM.EventMathEvent(
  "portfolio website",
  "promotion channel",
  {
    name: "portfolio website",
    direction: "direct",
    lens: "what",
    cost: "low",
    competition: "very high",
    saturation: "yes",
  }
);

// Event: "linkedin cold outreach"
const linkedin_cold_outreach = new EM.EventMathEvent(
  "linkedin cold outreach",
  "promotion channel",
  {
    name: "linkedin cold outreach",
    direction: "direct",
    lens: "who",
    cost: "medium",
    competition: "high",
    saturation: "yes",
  }
);

// Event: "cold email campaign"
const cold_email_campaign = new EM.EventMathEvent(
  "cold email campaign",
  "promotion channel",
  {
    name: "cold email campaign",
    direction: "direct",
    lens: "who",
    cost: "low",
    competition: "high",
    saturation: "yes",
  }
);

// Event: "new business trigger"
const new_business_trigger = new EM.EventMathEvent(
  "new business trigger",
  "innovative channel",
  {
    name: "new business registration targeting",
    direction: "indirect other",
    lens: "when",
    cost: "low",
    competition: "very low",
    saturation: "no",
    "why it works": "caught before they made any decisions",
  }
);

// Event: "bad review trigger"
const bad_review_trigger = new EM.EventMathEvent(
  "bad review trigger",
  "innovative channel",
  {
    name: "post bad review outreach",
    direction: "indirect other",
    lens: "why",
    cost: "very low",
    competition: "none",
    saturation: "no",
    "why it works": "speaking to the wound at the exact moment of pain",
  }
);

// Event: "competitor launched trigger"
const competitor_launched_trigger = new EM.EventMathEvent(
  "competitor launched trigger",
  "innovative channel",
  {
    name: "competitor site launch targeting",
    direction: "indirect other",
    lens: "when",
    cost: "low",
    competition: "none",
    saturation: "no",
    "why it works": "fear of falling behind is stronger than desire to improve",
  }
);

// Event: "prediction offer lead"
const prediction_offer_lead = new EM.EventMathEvent(
  "prediction offer lead",
  "innovative channel",
  {
    name: "free prediction audit offer",
    direction: "indirect other",
    lens: "what",
    cost: "very low",
    competition: "none",
    saturation: "no",
    "why it works": "gives value first filters serious buyers positions as strategist",
  }
);

// Event: "hiring signal trigger"
const hiring_signal_trigger = new EM.EventMathEvent(
  "hiring signal trigger",
  "innovative channel",
  {
    name: "growing company job posting trigger",
    direction: "indirect other",
    lens: "when",
    cost: "low",
    competition: "very low",
    saturation: "no",
    "why it works": "growing companies always need better web presence",
  }
);

// Event: "embarrassment angle"
const embarrassment_angle = new EM.EventMathEvent(
  "embarrassment angle",
  "innovative channel",
  {
    name: "embarrassment trigger ad",
    direction: "indirect other",
    lens: "why",
    cost: "medium",
    competition: "very low",
    saturation: "no",
    "why it works": "taps the real reason people hire web developers",
  }
);

// Layer: "saturated channels"
const saturated_channels = new EM.EventMathLayer("saturated channels", [
  google_search_ads,
  portfolio_website,
  linkedin_cold_outreach,
  cold_email_campaign,
]);

// Layer: "innovative channels"
const innovative_channels = new EM.EventMathLayer("innovative channels", [
  new_business_trigger,
  bad_review_trigger,
  competitor_launched_trigger,
  prediction_offer_lead,
  hiring_signal_trigger,
  embarrassment_angle,
]);

// Timeline: "promotion history"
const promotion_history = new EM.EventMathTimeline("promotion history");

promotion_history.log.push(...saturated_channels.events);

// predict: "promotion approach for web development" → all promotion predictions
const all_promotion_predictions = new EM.EventMathLayer('all promotion predictions', []);
directions.events.forEach(_dir => {
  lenses.events.forEach(_lens => {
    quantities.events.forEach(_qty => {
      all_promotion_predictions.events.push(new EM.EventMathEvent(
        'prediction_' + Date.now() + '_' + Math.random().toString(36).slice(2),
        'prediction',
        {
          subject: 'promotion approach for web development',
          direction: _dir.matter ? _dir.matter.name : String(_dir.id),
          lens: _lens.matter ? _lens.matter.name : String(_lens.id),
          quantity: _qty.matter ? _qty.matter.name : String(_qty.id),
          predicted_state: (_dir.matter ? _dir.matter.name : '') + ' change through ' + (_lens.matter ? _lens.matter.name : '') + ' lens affecting ' + (_qty.matter ? _qty.matter.name : ''),
          confidence: 0.5,
          resolved: false,
          correct: null
        }
      ));
    });
  });
});

// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "direct") && (_p.matter.lens === "where")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "direct") && (_p.matter.lens === "who")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "direct") && (_p.matter.lens === "what")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "more same") && (_p.matter.lens === "where")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "keep same") && (_p.matter.lens === "who")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: false }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "indirect opposite") && (_p.matter.lens === "why")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "indirect other") && (_p.matter.lens === "when")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
// resolve: all promotion predictions
all_promotion_predictions.events = all_promotion_predictions.events.map(_p => {
  if ((_p.matter.direction === "indirect other") && (_p.matter.lens === "why")) {
    return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: true }));
  }
  return _p;
});
direct_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.direction === "direct"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
indirect_other_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.direction === "indirect other"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
indirect_opposite_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.direction === "indirect opposite"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
keep_same_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.direction === "keep same"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
who_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "who"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
what_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "what"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
timing_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "when"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
why_accuracy = (function() {
  const _resolved = all_promotion_predictions.events.filter(_p => _p.matter.resolved === true && (_p.matter.lens === "why"));
  const _correct = _resolved.filter(_p => _p.matter.correct === true);
  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;
})();
let untapped_count = innovative_channels.events.filter(evt => evt.matter.saturation === "no").length;
let zero_competition_count = innovative_channels.events.filter(evt => evt.matter.competition === "none").length;
// zoom in on new business trigger and prediction offer lead into innovation gap
const innovation_gap = new EM.EventMathTimeline('innovation gap');
innovation_gap.zoomLevel = ((new_business_trigger.zoomLevel || 1) + 1);
const _ctrl_matter_innovation_gap = {
  from: new_business_trigger.id,
  to: prediction_offer_lead.id,
  zoom_level: innovation_gap.zoomLevel,
  control: true,
  gap_description: 'between new business trigger and prediction offer lead'
};
Object.keys(new_business_trigger.matter || {}).forEach(k => { _ctrl_matter_innovation_gap['from_' + k] = new_business_trigger.matter[k]; });
Object.keys(prediction_offer_lead.matter || {}).forEach(k => { _ctrl_matter_innovation_gap['to_' + k] = prediction_offer_lead.matter[k]; });
innovation_gap.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_innovation_gap)));

// zoom out on timeline promotion history as event current strategy summary
const current_strategy_summary = new EM.EventMathEvent(
  'current strategy summary',
  'summary',
  {
    source_type: 'timeline',
    source_name: 'promotion history',
    zoom_level: Math.max(1, (promotion_history.zoomLevel || 1) - 1),
    entry_count: promotion_history.log.length,
    summary: promotion_history.render()
  }
);

if (!(untapped_count > 0)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "untapped count is greater than 0",
    hint: "This condition was expected to be true.",
  }).render());
}
if (!(zero_competition_count > 0)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "zero competition count is greater than 0",
    hint: "This condition was expected to be true.",
  }).render());
}
// note: ── Prediction Results ──
{ const __sv = direct_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('direct accuracy:', __sv); } }
{ const __sv = indirect_other_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('indirect other accuracy:', __sv); } }
{ const __sv = indirect_opposite_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('indirect opposite accuracy:', __sv); } }
{ const __sv = keep_same_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('keep same accuracy:', __sv); } }
// note: ── Lens Scores ──
{ const __sv = who_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('who accuracy:', __sv); } }
{ const __sv = what_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('what accuracy:', __sv); } }
{ const __sv = timing_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('timing accuracy:', __sv); } }
{ const __sv = why_accuracy; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('why accuracy:', __sv); } }
// note: ── Channel Counts ──
{ const __sv = untapped_count; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('untapped count:', __sv); } }
{ const __sv = zero_competition_count; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('zero competition count:', __sv); } }
console.log(promotion_history.renderSection('past'));
console.log(promotion_history.renderSection('future'));
console.log(innovation_gap.renderSection('present'));
console.log(current_strategy_summary.render());

// ── Export for use ─────────────────────────────────
module.exports = {
  google_search_ads,
  portfolio_website,
  linkedin_cold_outreach,
  cold_email_campaign,
  new_business_trigger,
  bad_review_trigger,
  competitor_launched_trigger,
  prediction_offer_lead,
  hiring_signal_trigger,
  embarrassment_angle,
  current_strategy_summary,
  saturated_channels,
  innovative_channels,
  all_promotion_predictions,
  promotion_history,
  innovation_gap,
};