// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

let bridge_depth = (alpha_beta_bridge.zoomLevel || 1);

// note: Zoom Investigation — finding the control between parallel timelines
// note: Two parallel processes running at the same time
// Timeline: "process alpha"
const process_alpha = new EM.EventMathTimeline("process alpha");


// Timeline: "process beta"
const process_beta = new EM.EventMathTimeline("process beta");


// note: The space between two parallel timelines is also a timeline
// zoom in on process alpha and process beta into alpha beta bridge
const alpha_beta_bridge = new EM.EventMathTimeline('alpha beta bridge');
alpha_beta_bridge.zoomLevel = ((process_alpha.zoomLevel || 1) + 1);
const _ctrl_matter_alpha_beta_bridge = {
  from: process_alpha.name,
  to: process_beta.name,
  zoom_level: alpha_beta_bridge.zoomLevel,
  control: true,
  gap_description: 'between process alpha and process beta'
};
alpha_beta_bridge.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_alpha_beta_bridge)));

// note: What we find in the bridge is the indirect other — the connection
// note: that wasn't obvious from either track alone
if (!(bridge_depth > 1)) {
  console.error(new EM.EventMathEvent("check failed", "broken", {
    condition: "bridge depth is greater than 1",
    hint: "This condition was expected to be true.",
  }).render());
}
console.log(alpha_beta_bridge.renderSection('present'));