// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

let start_date = "2026-01-01";
let today_date = (new Date().toISOString().slice(0,10));
let days_passed = (Math.round(Math.abs(new Date(today_date) - new Date(start_date)) / 86400000));

// note: Date operations acceptance test
// Event: "project started"
const project_started = new EM.EventMathEvent(
  "project started",
  "timeline",
  {
    start: "start date",
    today: "today date",
    elapsed: "days passed",
  }
);

console.log(project_started.render());

// ── Export for use ─────────────────────────────────
module.exports = {
  project_started,
};