// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

// note: Layer operations acceptance test
// Event: "task one"
const task_one = new EM.EventMathEvent(
  "task one",
  "work",
  {
    priority: "high",
    status: "todo",
  }
);

// Event: "task two"
const task_two = new EM.EventMathEvent(
  "task two",
  "work",
  {
    priority: "low",
    status: "done",
  }
);

// Event: "task three"
const task_three = new EM.EventMathEvent(
  "task three",
  "work",
  {
    priority: "high",
    status: "done",
  }
);

// Layer: "all tasks"
const all_tasks = new EM.EventMathLayer("all tasks", [
  task_one,
  task_two,
  task_three,
]);

const completed_tasks = new EM.EventMathLayer("completed tasks",
  all_tasks.events.filter(evt => evt.matter.status === "done"));
let urgent_task = all_tasks.events.find(evt => evt.matter.priority === "high") || null;
let done_count = all_tasks.events.filter(evt => evt.matter.status === "done").length;

// ── Export for use ─────────────────────────────────
module.exports = {
  task_one,
  task_two,
  task_three,
  all_tasks,
  completed_tasks,
};