// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../runtime/eventmath-runtime.js');

let raw_score = (87 + 12) / 2;
let final_score = Math.round(raw_score);
let bonus_cap = Math.min(50, final_score);
let max_award = Math.max(100, final_score);
let dice_roll = (Math.floor(Math.random() * (6 - 1 + 1)) + 1);

// note: Math operations acceptance test
// Event: "score recorded"
const score_recorded = new EM.EventMathEvent(
  "score recorded",
  "math test",
  {
    score: "final score",
    bonus: "bonus cap",
  }
);

console.log(score_recorded.render());

// ── Export for use ─────────────────────────────────
module.exports = {
  score_recorded,
};