/**
 * EventMath Code Generator v0.4
 *
 * Walks the AST and emits plain, readable JavaScript.
 * Events → JS objects via runtime constructors
 * Actions → JS functions
 * Loops → for/while
 * Conditionals → if/else/switch
 * Timeline-tracked operations → runtime timeline methods
 *
 * Design: one AST node → one JS output string. Recursive generation.
 *
 * v0.2 fixes:
 *  - Escape all declaration names (event, category, layer, timeline) to prevent RCE
 *  - Escape rewind/forward destinations
 *  - Match action-call args by key (door input order), not source position
 *  - Hoist let declarations to top scope (fix ReferenceError in loops)
 *  - Add Stop codegen case (was silently dropped)
 *
 * v0.4 additions:
 *  - _genExpr() / _exprOperand() for arithmetic expressions
 *  - Updated _genSet() and _firstPass() for expr support
 *  - _genBrokenEvent() for broken event statement
 *  - Improved _genRun() using .render() on events/layers/timelines
 */

class EventMathCodeGen {
  constructor() {
    this.output = [];
    this.indent = 0;
    this._vars = new Set(); // Track declared variables
    this._varDecls = [];    // Hoisted let declarations (name, value) for top-level
    this._inAction = false; // Are we inside an action body?
    this._eventNames = new Set(); // Top-level event declarations
    this._layerNames = new Set();
    this._timelineNames = new Set();
    this._actionNames = new Set();
    this._actionDoorInputs = {}; // Map action name -> ordered input names
  }

  _line(code) {
    this.output.push('  '.repeat(this.indent) + code);
  }

  _lines(lines) {
    for (const line of lines) {
      this._line(line);
    }
  }

  /**
   * Generate JavaScript from an EventMath AST.
   * @param {object} ast - Program AST from the parser
   * @returns {string} Compiled JavaScript source
   */
  generate(ast) {
    this.output = [];
    this.indent = 0;
    this._vars = new Set();
    this._varDecls = [];
    this._inAction = false;
    this._eventNames = new Set();
    this._layerNames = new Set();
    this._timelineNames = new Set();
    this._actionNames = new Set();
    this._actionDoorInputs = {};

    // Header
    this._line('// Generated by EventMath Compiler v0.4');
    this._line('// Runtime: <script src="eventmath-runtime.js"></script>');
    this._line('');

    // Import/find runtime — assume available globally or require
    this._line("const EM = typeof EventMathRuntime !== 'undefined'");
    this._line("  ? EventMathRuntime");
    this._line("  : require('../runtime/eventmath-runtime.js');");
    this._line('');

    // First pass: register all declaration names and door inputs
    this._firstPass(ast.statements);

    // Emit hoisted variable declarations (marks/sets discovered during first pass)
    if (this._varDecls.length > 0) {
      for (const decl of this._varDecls) {
        const safe = this._safeName(decl.name);
        const val = decl.rawExpr !== undefined ? decl.rawExpr : decl.value;
        this._line(`let ${safe} = ${val !== undefined ? val : 'undefined'};`);
      }
      this._line('');
    }

    // Second pass: generate code
    this._hasOverlap = this._detectOverlap(ast.statements);
    if (this._hasOverlap) {
      this._line('(async () => {');
      this.indent++;
    }

    for (const stmt of ast.statements) {
      this._genStatement(stmt);
    }

    if (this._hasOverlap) {
      this.indent--;
      this._line('})().catch(err => {');
      this._line('  console.error(\'Broken event:\', err.message);');
      this._line('});');
    }

    // Template for acceptance test outputs
    if (this._eventNames.size > 0 || this._layerNames.size > 0) {
      this._line('');
      this._line('// ── Export for use ─────────────────────────────────');
      this._line('module.exports = {');
      this.indent++;
      for (const name of this._eventNames) {
        this._line(`${this._safeName(name)},`);
      }
      for (const name of this._layerNames) {
        this._line(`${this._safeName(name)},`);
      }
      for (const name of this._timelineNames) {
        this._line(`${this._safeName(name)},`);
      }
      for (const name of this._actionNames) {
        this._line(`${this._camelName(name)},`);
      }
      this.indent--;
      this._line('};');
    }

    return this.output.join('\n');
  }

  /**
   * First pass: register declaration names and door inputs.
   */
  _firstPass(statements) {
    for (const stmt of statements) {
      switch (stmt.type) {
        case 'Event':
          this._eventNames.add(stmt.name);
          break;
        case 'Layer':
          this._layerNames.add(stmt.name);
          break;
        case 'Timeline':
          this._timelineNames.add(stmt.name);
          break;
        case 'Action':
          this._actionNames.add(stmt.name);
          if (stmt.doorOpen && stmt.doorOpen.inputs.length > 0) {
            this._actionDoorInputs[stmt.name] = stmt.doorOpen.inputs;
          }
          break;
        case 'Mark':
          if (!this._vars.has(stmt.name)) {
            this._vars.add(stmt.name);
            if (stmt.expr) {
              this._varDecls.push({ name: stmt.name, rawExpr: this._genExpr(stmt.expr) });
            } else {
              this._varDecls.push({ name: stmt.name, value: this._typedValueFromString(stmt.value) });
            }
          }
          break;
        case 'Set':
          if (!this._vars.has(stmt.name)) {
            this._vars.add(stmt.name);
            this._varDecls.push({ name: stmt.name, value: undefined });
          }
          break;
        // Recurse into blocks so nested marks/sets are hoisted
        case 'When':
          this._firstPass(stmt.body || []);
          this._firstPass(stmt.otherwise || []);
          break;
        case 'AgainCount':
        case 'AgainUntil':
        case 'Walk':
          this._firstPass(stmt.body || []);
          break;
        case 'Overlap':
          for (const track of (stmt.tracks || [])) this._firstPass(track);
          break;
      }
    }
  }

  /**
   * Generate JS for a single statement (top-level or body).
   */
  _genStatement(stmt, inAction = false) {
    if (!stmt) return;

    switch (stmt.type) {
      case 'Event':          return this._genEvent(stmt, inAction);
      case 'Layer':          return this._genLayer(stmt);
      case 'Timeline':       return this._genTimeline(stmt);
      case 'Action':         return this._genAction(stmt);
      case 'Mark':           return this._genMark(stmt);
      case 'Set':            return this._genSet(stmt);
      case 'Run':            return this._genRun(stmt);
      case 'When':           return this._genWhen(stmt);
      case 'Split':          return this._genSplit(stmt);
      case 'AgainCount':     return this._genAgainCount(stmt);
      case 'AgainUntil':     return this._genAgainUntil(stmt);
      case 'Walk':           return this._genWalk(stmt);
      case 'ActionCall':     return this._genActionCall(stmt, inAction);
      case 'Rewind':         return this._genRewind(stmt);
      case 'Forward':        return this._genForward(stmt);
      case 'Stop':           return this._genStop(stmt);
      case 'AddEvent':       return this._genAddEvent(stmt);
      case 'AddLayer':       return this._genAddLayer(stmt);
      case 'RemoveLayer':    return this._genRemoveLayer(stmt);
      case 'RemoveEvent':    return this._genRemoveEvent(stmt);
      case 'Merge':          return this._genMerge(stmt);
      case 'Overlap':        return this._genOverlap(stmt);
      case 'Note':           return this._genNote(stmt);
      case 'BrokenEvent':    return this._genBrokenEvent(stmt);
      case 'NameRef':        return null; // standalone names are no-ops
      default:
        this._line(`// (unknown node type: ${stmt.type})`);
    }
  }

  // ── Events ──────────────────────────────────────────────────────

  _genEvent(stmt, inAction) {
    if (inAction) {
      // Inside an action: create event at runtime (spec: Law 6)
      return this._genInlineEvent(stmt);
    }

    // Top-level: static event declaration
    const varName = this._safeName(stmt.name);
    this._line(`// Event: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${this._escape(stmt.name)}",`);
    this._line(`"${this._escape(stmt.category || 'event')}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          // Reference — depends on context at runtime
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line('');
  }

  _genInlineEvent(stmt) {
    // Inside action: emit runtime constructor call
    const varName = this._safeName(stmt.name);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${this._escape(stmt.name)}",`);
    this._line(`"${this._escape(stmt.category || 'event')}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line(`EM.getDefaultTimeline().append(new EM.TimelineEntry("event", ${varName}));`);
  }

  // ── Layers ──────────────────────────────────────────────────────

  _genLayer(stmt) {
    const varName = this._safeName(stmt.name);
    this._line(`// Layer: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathLayer("${this._escape(stmt.name)}", [`);

    if (stmt.events && stmt.events.length > 0) {
      this.indent++;
      for (const evt of stmt.events) {
        this._line(`${this._safeName(evt.name)},`);
      }
      this.indent--;
    }

    this._line(`]);`);
    this._line('');
  }

  // ── Timelines ───────────────────────────────────────────────────

  _genTimeline(stmt) {
    const varName = this._safeName(stmt.name);
    this._line(`// Timeline: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathTimeline("${this._escape(stmt.name)}");`);
    this._line('');

    // Populate present layers
    if (stmt.present && stmt.present.layers) {
      for (const layer of stmt.present.layers) {
        this._line(`${varName}.log.push(...${this._safeName(layer.name)}.events);`);
      }
    }
    this._line('');
  }

  // ── Actions ─────────────────────────────────────────────────────

  _genAction(stmt) {
    const fnName = this._camelName(stmt.name);
    this._line(`// Action: "${this._escape(stmt.name)}"`);
    this._line(`function ${fnName}(`);

    // Door open params
    if (stmt.doorOpen && stmt.doorOpen.inputs.length > 0) {
      this._line(stmt.doorOpen.inputs.map(p => this._safeRef(p)).join(', '));
    }
    this._line(`) {`);
    this.indent++;

    // Body statements
    this._inAction = true;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, true);
    }
    this._inAction = false;

    // Door closed — return value
    if (stmt.doorClosed) {
      if (stmt.doorClosed.returns) {
        this._line(`return ${this._safeName(stmt.doorClosed.returns)};`);
      } else {
        this._line(`return;`);
      }
    }

    this.indent--;
    this._line(`}`);
    this._line('');
  }

  // ── Mark & Set ──────────────────────────────────────────────────

  _genMark(stmt) {
    // Declaration was already hoisted during first pass
    // No need to emit let — just the initial value is inline in the hoist
  }

  _typedValueFromString(str) {
    if (!str) return '""';
    if (str === 'true') return 'true';
    if (str === 'false') return 'false';
    if (/^\d+(\.\d+)?$/.test(str)) return str;
    return `"${this._escape(str)}"`;
  }

  _genSet(stmt) {
    const varName = this._safeName(stmt.name);
    // Declaration was already hoisted during first pass
    if (stmt.expr) {
      this._line(`${varName} = ${this._genExpr(stmt.expr)};`);
    } else {
      const val = this._typedValue(stmt.value);
      this._line(`${varName} = ${val};`);
    }
  }

  _typedValue(value) {
    if (!value) return '""';
    if (value.kind === 'number') return value.value;
    if (value.kind === 'bool') return value.value ? 'true' : 'false';
    if (value.kind === 'name') return this._safeRef(value.value);
    // Literal — detect boolean/number strings
    const raw = value.value || '';
    if (raw === 'true') return 'true';
    if (raw === 'false') return 'false';
    if (/^\d+(\.\d+)?$/.test(raw)) return raw;
    return `"${this._escape(raw)}"`;
  }

  // ── Arithmetic expressions ───────────────────────────────────────

  _genExpr(expr) {
    const ops = { plus: '+', minus: '-', times: '*', 'divided by': '/' };
    const jsOp = ops[expr.op] || '+';
    const left = this._exprOperand(expr.left);
    const right = this._exprOperand(expr.right);
    return `${left} ${jsOp} ${right}`;
  }

  _exprOperand(operand) {
    if (!operand) return '0';
    if (operand.kind === 'number') return operand.value;
    if (operand.kind === 'name') return this._safeRef(operand.value);
    return `"${this._escape(operand.value)}"`;
  }

  // ── Run ─────────────────────────────────────────────────────────

  _genRun(stmt) {
    if (!stmt.target) {
      this._line(`console.log('');`);
      return;
    }
    const words = stmt.target.split(' ');
    const kind = words[0];
    const name = words.slice(1).join(' ') || words[0];

    if (kind === 'event') {
      this._line(`console.log(${this._safeName(name)}.render());`);
    } else if (kind === 'layer') {
      this._line(`console.log(${this._safeName(name)}.render());`);
    } else if (kind === 'timeline') {
      this._line(`console.log(${this._safeName(name)}.render());`);
    } else {
      // Timeline section: "story present" or "story past"
      const parts = stmt.target.split(' ');
      const section = parts[parts.length - 1];
      const timelineName = parts.slice(0, parts.length - 1).join(' ');
      if (['past', 'present', 'future'].includes(section)) {
        this._line(`console.log(${this._safeName(timelineName)}.renderSection('${section}'));`);
      } else {
        this._line(`console.log(${this._safeName(stmt.target)}.render());`);
      }
    }
  }

  // ── Conditionals ────────────────────────────────────────────────

  _genWhen(stmt) {
    if (!stmt.condition) {
      this._line(`// (when with no condition)`);
      return;
    }
    const cond = this._genCondition(stmt.condition);
    this._line(`if (${cond}) {`);
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;

    if (stmt.otherwise && stmt.otherwise.length > 0) {
      this._line(`} else {`);
      this.indent++;
      for (const bodyStmt of stmt.otherwise) {
        this._genStatement(bodyStmt, this._inAction);
      }
      this.indent--;
    }

    this._line(`}`);
  }

  _genCondition(cond) {
    const left = this._walkRef(cond.left);
    const rightVal = cond.right || '';

    // For numeric operators, emit the right-hand side as a number if it looks numeric
    const numericOps = new Set(['greater than', 'less than', 'at least', 'at most']);
    let right;
    if (rightVal === 'true') right = 'true';
    else if (rightVal === 'false') right = 'false';
    else if (/^\d+(\.\d+)?$/.test(rightVal)) right = rightVal;
    else if (numericOps.has(cond.op) && /^\d+(\.\d+)?$/.test(rightVal)) right = rightVal;
    else right = `"${this._escape(rightVal)}"`;

    const ops = {
      'is': '===',
      'is not': '!==',
      'greater than': '>',
      'less than': '<',
      'at least': '>=',
      'at most': '<=',
    };
    const jsOp = ops[cond.op] || '===';
    return `${left} ${jsOp} ${right}`;
  }

  /**
   * Resolve a name reference, supporting walk variable property access.
   * "current task status" → "current_task.status" when walkVar = "current task"
   */
  _walkRef(name) {
    if (!this._walkVar || !name) return this._safeRef(name);
    const walkVarSafe = this._safeName(this._walkVar);
    if (name === this._walkVar) return walkVarSafe;
    const prefix = this._walkVar;
    if (name.startsWith(prefix + ' ')) {
      const rest = name.slice(prefix.length).trim();
      if (rest) {
        return `${walkVarSafe}.matter.${this._safeName(rest)}`;
      }
      return walkVarSafe;
    }
    return this._safeRef(name);
  }

  // ── Split ──────────────────────────────────────────────────────

  _genSplit(stmt) {
    const target = this._safeRef(stmt.target);
    this._line(`// split ${target}`);
    this._line(`switch (${target}) {`);
    this.indent++;

    for (const path of (stmt.paths || [])) {
      this._line(`case "${this._escape(path.name)}":`);
      this.indent++;
      for (const bodyStmt of (path.body || [])) {
        this._genStatement(bodyStmt, this._inAction);
      }
      this._line(`break;`);
      this.indent--;
    }

    this.indent--;
    this._line(`}`);
  }

  // ── Loops ──────────────────────────────────────────────────────

  _genAgainCount(stmt) {
    const count = stmt.count || 0;
    this._line(`for (let __i = 0; __i < ${count}; __i++) {`);
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;
    this._line(`}`);
  }

  _genAgainUntil(stmt) {
    if (!stmt.condition) {
      this._line(`while (true) {`);
    } else {
      const cond = this._genCondition(stmt.condition);
      // Invert: "again until X is true" = "while (!X)"
      this._line(`while (!(${cond})) {`);
    }
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;
    this._line(`}`);
  }

  _genWalk(stmt) {
    const layer = this._safeName(stmt.layer);
    const variable = this._safeName(stmt.variable);
    this._walkVar = stmt.variable; // Track for property access in conditions
    this._line(`for (const ${variable} of ${layer}.events) {`);
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;
    this._line(`}`);
    this._walkVar = null;
  }

  // ── Stop ────────────────────────────────────────────────────────

  _genStop(stmt) {
    // Emit return (works in both functions and top-level scripts)
    this._line(`return;`);
  }

  // ── Action calls ────────────────────────────────────────────────

  _genActionCall(stmt, inAction) {
    const fnName = this._camelName(stmt.name);
    const doorInputs = this._actionDoorInputs[stmt.name] || [];
    const argMap = {}; // key -> value
    for (const arg of (stmt.args || [])) {
      argMap[arg.key] = arg.value;
    }
    // Emit args in door input order, matching by key
    const args = doorInputs.map(key => {
      const val = argMap[key];
      if (val !== undefined) {
        return `"${this._escape(val)}"`;
      }
      return 'undefined';
    });
    this._line(`${fnName}(${args.join(', ')});`);
  }

  // ── Time travel ────────────────────────────────────────────────

  _genRewind(stmt) {
    const target = this._safeName(stmt.target);
    if (stmt.mode === 'by') {
      this._line(`${target}.rewind(${stmt.count || 1});`);
    } else if (stmt.mode === 'to') {
      this._line(`${target}.rewindTo("${this._escape(stmt.destination)}");`);
    }
  }

  _genForward(stmt) {
    const target = this._safeName(stmt.target);
    if (stmt.mode === 'by') {
      this._line(`${target}.forward(${stmt.count || 1});`);
    } else if (stmt.mode === 'to') {
      this._line(`${target}.forwardTo("${this._escape(stmt.destination)}");`);
    }
  }

  // ── Layer operations ──────────────────────────────────────────

  _genAddEvent(stmt) {
    const eventName = this._safeName(stmt.eventName);
    const layerName = this._safeName(stmt.layerName);
    if (layerName) {
      this._line(`${layerName}.events.push(${eventName});`);
    }
  }

  _genAddLayer(stmt) {
    this._line(`// add layer: ${stmt.layerName}`);
  }

  _genRemoveLayer(stmt) {
    this._line(`// remove layer: ${stmt.name}`);
  }

  _genRemoveEvent(stmt) {
    this._line(`// remove event: ${stmt.name}`);
  }

  _genMerge(stmt) {
    this._line(`// merge ${stmt.source} into ${stmt.target}`);
  }

  // ── Broken Event ───────────────────────────────────────────────

  _genBrokenEvent(stmt) {
    const varName = this._safeName(stmt.name);
    this._line(`// broken event: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${this._escape(stmt.name)}",`);
    this._line(`"broken",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line(`console.error(${varName}.render());`);
    this._line('');
  }

  // ── Overlap & Note ─────────────────────────────────────────────

  /**
   * Recursively checks whether any node in the AST is an Overlap.
   */
  _detectOverlap(statements) {
    if (!statements) return false;
    for (const stmt of statements) {
      if (!stmt) continue;
      if (stmt.type === 'Overlap') return true;
      // Check nested bodies
      if (stmt.body && this._detectOverlap(stmt.body)) return true;
      if (stmt.otherwise && this._detectOverlap(stmt.otherwise)) return true;
      if (stmt.tracks) {
        for (const track of stmt.tracks) {
          if (this._detectOverlap(track)) return true;
        }
      }
      // Check path bodies in split
      if (stmt.paths) {
        for (const path of stmt.paths) {
          if (path.body && this._detectOverlap(path.body)) return true;
        }
      }
    }
    return false;
  }

  _genOverlap(stmt) {
    this._line('// overlap: run these tracks at the same time');
    this._line('await Promise.all([');
    this.indent++;
    for (const track of (stmt.tracks || [])) {
      this._line('(async () => {');
      this.indent++;
      for (const s of track) this._genStatement(s, this._inAction);
      this.indent--;
      this._line('})(),');
    }
    this.indent--;
    this._line(']);');
  }

  _genNote(stmt) {
    this._line(`// note: ${stmt.text}`);
  }

  // ── Helpers ─────────────────────────────────────────────────────

  _safeName(name) {
    if (!name) return '__empty';
    // Convert "User can log in" → "User_can_log_in"
    // Prefix with __ if it starts with a digit
    let s = name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_$]/g, '');
    if (/^\d/.test(s)) s = '_' + s;
    if (/^[a-zA-Z_$]/.test(s)) return s;
    return '_' + s;
  }

  _safeKey(key) {
    if (!key) return '"_empty"';
    // Object keys that aren't valid JS identifiers need quoting
    const idRegex = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
    if (idRegex.test(key)) return key;
    return `"${key}"`;
  }

  _safeRef(name) {
    if (!name) return 'undefined';
    const safe = this._safeName(name);
    if (safe === 'true' || safe === 'false') return safe;
    if (safe === 'undefined') return 'undefined';
    return safe;
  }

  _camelName(name) {
    // "make requirement" → "makeRequirement"
    if (!name) return 'unnamed';
    return name.split(/\s+/).map((w, i) =>
      i === 0 ? w.replace(/[^a-zA-Z0-9_$]/g, '') :
        w.charAt(0).toUpperCase() + w.slice(1).replace(/[^a-zA-Z0-9_$]/g, '')
    ).join('');
  }

  _escape(str) {
    if (typeof str !== 'string') return String(str);
    return str.replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');
  }
}

module.exports = { EventMathCodeGen };
