/**
 * EventMath Code Generator v0.4
 *
 * Walks the AST and emits plain, readable JavaScript.
 * Events → JS objects via runtime constructors
 * Actions → JS functions
 * Loops → for/while
 * Conditionals → if/else/switch
 * Timeline-tracked operations → runtime timeline methods
 *
 * Design: one AST node → one JS output string. Recursive generation.
 *
 * v0.2 fixes:
 *  - Escape all declaration names (event, category, layer, timeline) to prevent RCE
 *  - Escape rewind/forward destinations
 *  - Match action-call args by key (door input order), not source position
 *  - Hoist let declarations to top scope (fix ReferenceError in loops)
 *  - Add Stop codegen case (was silently dropped)
 *
 * v0.4 additions:
 *  - _genExpr() / _exprOperand() for arithmetic expressions
 *  - Updated _genSet() and _firstPass() for expr support
 *  - _genBrokenEvent() for broken event statement
 *  - Improved _genRun() using .render() on events/layers/timelines
 */

class EventMathCodeGen {
  constructor() {
    this.output = [];
    this.indent = 0;
    this._vars = new Set(); // Track declared variables
    this._varDecls = [];    // Hoisted let declarations (name, value) for top-level
    this._inAction = false; // Are we inside an action body?
    this._eventNames = new Set(); // Top-level event declarations
    this._layerNames = new Set();
    this._timelineNames = new Set();
    this._actionNames = new Set();
    this._actionDoorInputs = {}; // Map action name -> ordered input names
    this._useStmts = [];          // Use/import statements
    this._importedNames = new Set(); // Names imported via use
  }

  _line(code) {
    this.output.push('  '.repeat(this.indent) + code);
  }

  _lines(lines) {
    for (const line of lines) {
      this._line(line);
    }
  }

  /**
   * Generate JavaScript from an EventMath AST.
   * @param {object} ast - Program AST from the parser
   * @returns {string} Compiled JavaScript source
   */
  generate(ast) {
    this.output = [];
    this.indent = 0;
    this._vars = new Set();
    this._varDecls = [];
    this._inAction = false;
    this._eventNames = new Set();
    this._layerNames = new Set();
    this._timelineNames = new Set();
    this._actionNames = new Set();
    this._actionDoorInputs = {};
    this._useStmts = [];
    this._importedNames = new Set();

    // Header
    this._line('// Generated by EventMath Compiler v0.4');
    this._line('// Runtime: <script src="eventmath-runtime.js"></script>');
    this._line('');

    // Import/find runtime — assume available globally or require
    this._line("const EM = typeof EventMathRuntime !== 'undefined'");
    this._line("  ? EventMathRuntime");
    this._line("  : require('../runtime/eventmath-runtime.js');");
    this._line('');
    // Probabilistic weight registry — populated by weight statements
    this._line('const __weights = {};');
    // Assumption registry — populated by assume statements, passed to satisfaction engine
    this._line('const __assumptions = [];');
    this._line('');

    // First pass: register all declaration names and door inputs
    this._firstPass(ast.statements);

    // Emit use/import statements
    if (this._useStmts.length > 0) {
      for (const stmt of this._useStmts) {
        this._genUse(stmt);
      }
      this._line('');
    }

    // Emit hoisted variable declarations (marks/sets discovered during first pass)
    // Complex expressions (rawExpr) are hoisted as undefined and assigned inline
    // to avoid referencing variables not yet defined at hoist time.
    if (this._varDecls.length > 0) {
      for (const decl of this._varDecls) {
        const safe = this._safeName(decl.name);
        if (decl.rawExpr !== undefined) {
          this._line(`let ${safe};`);
        } else {
          const val = decl.value;
          this._line(`let ${safe} = ${val !== undefined ? val : 'undefined'};`);
        }
      }
      this._line('');
    }

    // Second pass: generate code
    this._hasOverlap = this._detectOverlap(ast.statements);
    if (this._hasOverlap) {
      this._line('(async () => {');
      this.indent++;
    }

    for (const stmt of ast.statements) {
      this._genStatement(stmt);
    }

    if (this._hasOverlap) {
      this.indent--;
      this._line('})().catch(err => {');
      this._line('  console.error(\'Broken event:\', err.message);');
      this._line('});');
    }

    // Template for acceptance test outputs
    if (this._eventNames.size > 0 || this._layerNames.size > 0) {
      this._line('');
      this._line('// ── Export for use ─────────────────────────────────');
      this._line('module.exports = {');
      this.indent++;
      for (const name of this._eventNames) {
        this._line(`${this._safeName(name)},`);
      }
      for (const name of this._layerNames) {
        this._line(`${this._safeName(name)},`);
      }
      for (const name of this._timelineNames) {
        this._line(`${this._safeName(name)},`);
      }
      for (const name of this._actionNames) {
        this._line(`${this._camelName(name)},`);
      }
      this.indent--;
      this._line('};');
    }

    return this.output.join('\n');
  }

  /**
   * First pass: register declaration names and door inputs.
   */
  _firstPass(statements) {
    for (const stmt of statements) {
      switch (stmt.type) {
        case 'Event':
          this._eventNames.add(stmt.name);
          break;
        case 'Layer':
          this._layerNames.add(stmt.name);
          break;
        case 'Timeline':
          this._timelineNames.add(stmt.name);
          break;
        case 'Action':
          this._actionNames.add(stmt.name);
          if (stmt.doorOpen && stmt.doorOpen.inputs.length > 0) {
            this._actionDoorInputs[stmt.name] = stmt.doorOpen.inputs;
          }
          break;
        case 'Mark':
          if (!this._vars.has(stmt.name)) {
            this._vars.add(stmt.name);
            if (stmt.builtinExpr) {
              this._varDecls.push({ name: stmt.name, rawExpr: this._genBuiltinExpr(stmt.builtinExpr) });
            } else if (stmt.stringOp) {
              this._varDecls.push({ name: stmt.name, rawExpr: this._genStringOp(stmt) });
            } else if (stmt.expr) {
              this._varDecls.push({ name: stmt.name, rawExpr: this._genExpr(stmt.expr) });
            } else {
              this._varDecls.push({ name: stmt.name, value: this._typedValueFromString(stmt.value) });
            }
          }
          break;
        case 'Set':
          if (!this._vars.has(stmt.name)) {
            this._vars.add(stmt.name);
            this._varDecls.push({ name: stmt.name, value: undefined });
          }
          break;
        case 'Use':
          this._useStmts.push(stmt);
          // Mark the imported name as a known symbol so references don't error
          this._importedNames.add(stmt.name);
          break;
        case 'FilterLayer':
          if (stmt.into && !this._vars.has(stmt.into)) {
            this._vars.add(stmt.into);
            this._layerNames.add(stmt.into);
          }
          break;
        case 'PredictStmt':
          if (stmt.intoLayer && !this._vars.has(stmt.intoLayer)) {
            this._vars.add(stmt.intoLayer);
            this._layerNames.add(stmt.intoLayer);
          }
          break;
        case 'FindInLayer':
          if (stmt.into && !this._vars.has(stmt.into)) {
            this._vars.add(stmt.into);
            // Find targets are not full layers — don't add to _layerNames
          }
          break;
        case 'CountInLayer':
          if (stmt.into && !this._vars.has(stmt.into)) {
            this._vars.add(stmt.into);
            // Count targets are numeric marks
          }
          break;
        case 'ZoomIn':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            // layer→layer zoom creates a new layer; event→event and timeline→timeline create a timeline
            if (stmt.fromType === 'layer') {
              this._layerNames.add(stmt.intoName);
            } else {
              this._timelineNames.add(stmt.intoName);
            }
          }
          break;
        case 'ZoomOut':
          if (stmt.asName && !this._vars.has(stmt.asName)) {
            this._vars.add(stmt.asName);
            this._eventNames.add(stmt.asName);
          }
          break;
        case 'ZoomOpposite':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._timelineNames.add(stmt.intoName);
          }
          break;
        case 'ZoomMeta':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._timelineNames.add(stmt.intoName);
          }
          break;
        case 'SpinStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
          }
          break;
        case 'CycleStmt':
          break;
        case 'ExplainStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._eventNames.add(stmt.intoName);
          }
          break;
        case 'AnalogyStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
          }
          break;
        case 'LandscapeStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._varDecls.push({ name: this._safeName(stmt.intoName), value: 'null' });
          }
          break;
        case 'ForecastStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._varDecls.push({ name: this._safeName(stmt.intoName), value: 'null' });
          }
          break;
        case 'BoundStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._varDecls.push({ name: this._safeName(stmt.intoName), value: 'null' });
          }
          break;
        case 'AsymmetryStmt':
        case 'RootOfStmt':
        case 'InvertStmt':
        case 'DetectFallaciesStmt':
        case 'FractalStmt':
        case 'SatisfyStmt':
        case 'EvaluateStmt':
        case 'DimensionalStmt':
          if (stmt.intoName && !this._vars.has(stmt.intoName)) {
            this._vars.add(stmt.intoName);
            this._varDecls.push({ name: this._safeName(stmt.intoName), value: 'null' });
          }
          break;
        case 'AssumeStmt':
          if (stmt.name && !this._vars.has(stmt.name)) {
            this._vars.add(stmt.name);
            this._varDecls.push({ name: this._safeName(stmt.name), value: 'null' });
          }
          break;
        case 'ActorStmt':
          this._eventNames.add(stmt.name);
          break;
        case 'ChainStmt':
          if (!this._vars.has(stmt.name)) {
            this._vars.add(stmt.name);
            this._varDecls.push({ name: this._safeName(stmt.name), value: 'null' });
          }
          break;
        case 'EventLikeStmt':
          this._eventNames.add(stmt.name);
          break;
        // Recurse into blocks so nested marks/sets are hoisted
        case 'When':
          this._firstPass(stmt.body || []);
          this._firstPass(stmt.otherwise || []);
          break;
        case 'AgainCount':
        case 'AgainUntil':
        case 'Walk':
          this._firstPass(stmt.body || []);
          break;
        case 'Overlap':
          for (const track of (stmt.tracks || [])) this._firstPass(track);
          break;
      }
    }
  }

  /**
   * Generate JS for a single statement (top-level or body).
   */
  _genStatement(stmt, inAction = false) {
    if (!stmt) return;

    switch (stmt.type) {
      case 'Event':          return this._genEvent(stmt, inAction);
      case 'Layer':          return this._genLayer(stmt);
      case 'Timeline':       return this._genTimeline(stmt);
      case 'Action':         return this._genAction(stmt);
      case 'Mark':           return this._genMark(stmt);
      case 'Set':            return this._genSet(stmt);
      case 'Run':            return this._genRun(stmt);
      case 'Show':           return this._genShow(stmt);
      case 'When':           return this._genWhen(stmt);
      case 'Split':          return this._genSplit(stmt);
      case 'AgainCount':     return this._genAgainCount(stmt);
      case 'AgainUntil':     return this._genAgainUntil(stmt);
      case 'Walk':           return this._genWalk(stmt);
      case 'ActionCall':     return this._genActionCall(stmt, inAction);
      case 'Rewind':         return this._genRewind(stmt);
      case 'Forward':        return this._genForward(stmt);
      case 'Stop':           return this._genStop(stmt);
      case 'AddEvent':       return this._genAddEvent(stmt);
      case 'AddLayer':       return this._genAddLayer(stmt);
      case 'RemoveLayer':    return this._genRemoveLayer(stmt);
      case 'RemoveEvent':    return this._genRemoveEvent(stmt);
      case 'Merge':          return this._genMerge(stmt);
      case 'Overlap':        return this._genOverlap(stmt);
      case 'Note':           return this._genNote(stmt);
      case 'BrokenEvent':    return this._genBrokenEvent(stmt);
      case 'Check':          return this._genCheck(stmt);
      case 'Use':            return; // handled in first pass emit
      case 'NameRef':        return null; // standalone names are no-ops
      case 'SortLayer':      return this._genSortLayer(stmt);
      case 'FilterLayer':    return this._genFilterLayer(stmt);
      case 'FindInLayer':    return this._genFindInLayer(stmt);
      case 'CountInLayer':   return this._genCountInLayer(stmt);
      case 'PredictStmt':    return this._genPredictStmt(stmt);
      case 'ResolveStmt':    return this._genResolveStmt(stmt);
      case 'ZoomIn':         return this._genZoomIn(stmt);
      case 'ZoomOut':        return this._genZoomOut(stmt);
      case 'ZoomOpposite':   return this._genZoomOpposite(stmt);
      case 'ZoomMeta':       return this._genZoomMeta(stmt);
      case 'SpinStmt':       return this._genSpinStmt(stmt);
      case 'VibrateStmt':    return this._genVibrateStmt(stmt);
      case 'CycleStmt':      return this._genCycleStmt(stmt);
      case 'ResonateStmt':   return this._genResonateStmt(stmt);
      case 'WeightStmt':     return this._genWeightStmt(stmt);
      case 'ExplainStmt':    return this._genExplainStmt(stmt);
      case 'AnalogyStmt':    return this._genAnalogyStmt(stmt);
      case 'LandscapeStmt':  return this._genLandscapeStmt(stmt);
      case 'ForecastStmt':   return this._genForecastStmt(stmt);
      case 'BoundStmt':           return this._genBoundStmt(stmt);
      case 'ActorStmt':           return this._genActorStmt(stmt);
      case 'ChainStmt':           return this._genChainStmt(stmt);
      case 'EventLikeStmt':       return this._genEventLikeStmt(stmt);
      case 'AsymmetryStmt':       return this._genAsymmetryStmt(stmt);
      case 'RootOfStmt':          return this._genRootOfStmt(stmt);
      case 'InvertStmt':          return this._genInvertStmt(stmt);
      case 'AssumeStmt':          return this._genAssumeStmt(stmt);
      case 'DetectFallaciesStmt': return this._genDetectFallaciesStmt(stmt);
      case 'FractalStmt':         return this._genFractalStmt(stmt);
      case 'SatisfyStmt':         return this._genSatisfyStmt(stmt);
      case 'EvaluateStmt':        return this._genEvaluateStmt(stmt);
      case 'DimensionalStmt':     return this._genDimensionalStmt(stmt);
      default:
        this._line(`// (unknown node type: ${stmt.type})`);
    }
  }

  // ── Events ──────────────────────────────────────────────────────

  _genEvent(stmt, inAction) {
    if (inAction) {
      // Inside an action: create event at runtime (spec: Law 6)
      return this._genInlineEvent(stmt);
    }

    // Top-level: static event declaration
    const varName = this._safeName(stmt.name);
    this._line(`// Event: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${this._escape(stmt.name)}",`);
    this._line(`"${this._escape(stmt.category || 'event')}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          // Reference — depends on context at runtime
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line('');
  }

  _genInlineEvent(stmt) {
    // Inside action: emit runtime constructor call
    const varName = this._safeName(stmt.name);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${this._escape(stmt.name)}",`);
    this._line(`"${this._escape(stmt.category || 'event')}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line(`EM.getDefaultTimeline().append(new EM.TimelineEntry("event", ${varName}));`);
  }

  // ── Layers ──────────────────────────────────────────────────────

  _genLayer(stmt) {
    const varName = this._safeName(stmt.name);
    this._line(`// Layer: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathLayer("${this._escape(stmt.name)}", [`);

    if (stmt.events && stmt.events.length > 0) {
      this.indent++;
      for (const evt of stmt.events) {
        this._line(`${this._safeName(evt.name)},`);
      }
      this.indent--;
    }

    this._line(`]);`);
    this._line('');
  }

  // ── Timelines ───────────────────────────────────────────────────

  _genTimeline(stmt) {
    const varName = this._safeName(stmt.name);
    this._line(`// Timeline: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathTimeline("${this._escape(stmt.name)}");`);
    this._line('');

    // Populate present layers
    if (stmt.present && stmt.present.layers) {
      for (const layer of stmt.present.layers) {
        this._line(`${varName}.log.push(...${this._safeName(layer.name)}.events);`);
      }
    }
    this._line('');
  }

  // ── Actions ─────────────────────────────────────────────────────

  _genAction(stmt) {
    const fnName = this._camelName(stmt.name);
    this._line(`// Action: "${this._escape(stmt.name)}"`);
    this._line(`function ${fnName}(`);

    // Door open params
    if (stmt.doorOpen && stmt.doorOpen.inputs.length > 0) {
      this._line(stmt.doorOpen.inputs.map(p => this._safeRef(p)).join(', '));
    }
    this._line(`) {`);
    this.indent++;

    // Body statements
    this._inAction = true;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, true);
    }
    this._inAction = false;

    // Door closed — return value
    if (stmt.doorClosed) {
      if (stmt.doorClosed.returns) {
        this._line(`return ${this._safeName(stmt.doorClosed.returns)};`);
      } else {
        this._line(`return;`);
      }
    }

    this.indent--;
    this._line(`}`);
    this._line('');
  }

  // ── Mark & Set ──────────────────────────────────────────────────

  _genMark(stmt) {
    const varName = this._safeName(stmt.name);
    // For complex expressions (builtinExpr, stringOp, expr), the hoist only
    // emitted `let x;` — assign the value inline here where the mark appears.
    if (stmt.builtinExpr) {
      this._line(`${varName} = ${this._genBuiltinExpr(stmt.builtinExpr)};`);
    } else if (stmt.stringOp) {
      this._line(`${varName} = ${this._genStringOp(stmt)};`);
    } else if (stmt.expr) {
      this._line(`${varName} = ${this._genExpr(stmt.expr)};`);
    }
    // Simple value marks: already fully initialized in the hoist, no inline needed
  }

  _typedValueFromString(str) {
    if (!str) return '""';
    if (str === 'true') return 'true';
    if (str === 'false') return 'false';
    if (str === 'past')    return '-1';
    if (str === 'present') return '0';
    if (str === 'future')  return '1';
    if (/^-?\d+(\.\d+)?$/.test(str)) return str;
    return `"${this._escape(str)}"`;
  }

  _genSet(stmt) {
    const varName = this._safeName(stmt.name);
    // Declaration was already hoisted during first pass
    if (stmt.builtinExpr) {
      this._line(`${varName} = ${this._genBuiltinExpr(stmt.builtinExpr)};`);
    } else if (stmt.stringOp) {
      this._line(`${varName} = ${this._genStringOp(stmt)};`);
    } else if (stmt.expr) {
      this._line(`${varName} = ${this._genExpr(stmt.expr)};`);
    } else {
      const val = this._typedValue(stmt.value);
      this._line(`${varName} = ${val};`);
    }
  }

  _typedValue(value) {
    if (!value) return '""';
    if (value.kind === 'number') return value.value;
    if (value.kind === 'bool') return value.value ? 'true' : 'false';
    if (value.kind === 'name') {
      const n = value.value;
      if (n === 'past')    return '-1';
      if (n === 'present') return '0';
      if (n === 'future')  return '1';
      return this._safeRef(n);
    }
    // Literal — detect boolean/number strings
    const raw = value.value || '';
    if (raw === 'true') return 'true';
    if (raw === 'false') return 'false';
    if (raw === 'past')    return '-1';
    if (raw === 'present') return '0';
    if (raw === 'future')  return '1';
    if (/^-?\d+(\.\d+)?$/.test(raw)) return raw;
    return `"${this._escape(raw)}"`;
  }

  // ── String operations ────────────────────────────────────────────

  _genStringOp(stmt) {
    const { stringOp } = stmt;
    if (stringOp === 'joined with') {
      const l = this._safeRef(stmt.left.value);
      const r = /^\d+$/.test(stmt.right.value) ? stmt.right.value :
                (this._vars.has(stmt.right.value) ? this._safeRef(stmt.right.value) : `"${this._escape(stmt.right.value)}"`);
      return `String(${l}) + ${r}`;
    }
    if (stringOp === 'in uppercase') return `String(${this._safeRef(stmt.subject.value)}).toUpperCase()`;
    if (stringOp === 'in lowercase') return `String(${this._safeRef(stmt.subject.value)}).toLowerCase()`;
    if (stringOp === 'length of')    return `String(${this._safeRef(stmt.subject.value)}).length`;
    return '""';
  }

  // ── Built-in expressions ─────────────────────────────────────────

  /**
   * Resolve a word array operand to a JS expression string.
   * Single word: mark reference or number/string literal.
   * Multi-word: joined as a mark reference.
   */
  _resolveOperand(words) {
    if (!words || words.length === 0) return '""';
    const raw = words.join(' ');
    if (!raw) return '""';
    // Number literal
    if (/^\d+(\.\d+)?$/.test(raw)) return raw;
    // String literal (quoted)
    if (/^".*"$/.test(raw)) return raw;
    // Mark reference — convert to safe JS identifier
    return this._safeName(raw);
  }

  /**
   * Generate JS for a BuiltinExpr op object.
   */
  _genBuiltinExpr(op) {
    if (!op || !op.kind) return '""';
    const { kind } = op;

    if (kind === 'today') {
      return '(new Date().toISOString().slice(0,10))';
    }
    if (kind === 'now') {
      return '(new Date().toISOString())';
    }
    if (kind === 'round') {
      const a = this._resolveOperand(op.a);
      return `Math.round(${a})`;
    }
    if (kind === 'floor') {
      const a = this._resolveOperand(op.a);
      return `Math.floor(${a})`;
    }
    if (kind === 'ceiling') {
      const a = this._resolveOperand(op.a);
      return `Math.ceil(${a})`;
    }
    if (kind === 'absolute') {
      const a = this._resolveOperand(op.a);
      return `Math.abs(${a})`;
    }
    if (kind === 'min') {
      const a = this._resolveOperand(op.a);
      const b = this._resolveOperand(op.b);
      return `Math.min(${a}, ${b})`;
    }
    if (kind === 'max') {
      const a = this._resolveOperand(op.a);
      const b = this._resolveOperand(op.b);
      return `Math.max(${a}, ${b})`;
    }
    if (kind === 'random') {
      const a = this._resolveOperand(op.a);
      const b = this._resolveOperand(op.b);
      return `(Math.floor(Math.random() * (${b} - ${a} + 1)) + ${a})`;
    }
    if (kind === 'days_between') {
      const a = this._resolveOperand(op.a);
      const b = this._resolveOperand(op.b);
      return `(Math.round(Math.abs(new Date(${b}) - new Date(${a})) / 86400000))`;
    }
    if (kind === 'trimmed') {
      const a = this._resolveOperand(op.a);
      return `String(${a}).trim()`;
    }
    if (kind === 'repeated') {
      const a = this._resolveOperand(op.a);
      const n = this._resolveOperand(op.n);
      return `String(${a}).repeat(${n})`;
    }
    if (kind === 'accuracy_of') {
      const layerName = this._safeName(op.layer.join(' '));
      const condStr = (op.condition || []).join(' ');
      const cond = this._genMatterCondition(condStr, '_p');
      return `(function() {\n  const _resolved = ${layerName}.events.filter(_p => _p.matter.resolved === true && (${cond}));\n  const _correct = _resolved.filter(_p => _p.matter.correct === true);\n  return _resolved.length > 0 ? Math.round((_correct.length / _resolved.length) * 100) / 100 : 0;\n})()`;
    }
    if (kind === 'zoom_level_of') {
      const targetName = this._safeName(op.target);
      return `(${targetName}.zoomLevel || 1)`;
    }
    if (kind === 'dimension_of') {
      const targetName = this._safeName(op.target);
      return `(${targetName}.dimension || 2)`;
    }
    if (kind === 'sqrt') {
      const a = this._resolveOperand(op.a);
      return `Math.sqrt(${a})`;
    }
    if (kind === 'weighted_accuracy_of') {
      const layerName = this._safeName(op.layer.join(' '));
      const condStr = (op.condition || []).join(' ');
      const cond = this._genMatterCondition(condStr, '_p');
      return `(function() {\n  const _resolved = ${layerName}.events.filter(_p => _p.matter && _p.matter.resolved === true && (${cond}));\n  let _wCorrect = 0, _wTotal = 0;\n  for (const _p of _resolved) {\n    const _w = __weights[_p.matter.direction] || __weights[_p.matter.lens] || __weights[_p.matter.quantity] || 1;\n    _wTotal += _w;\n    if (_p.matter.correct === true) _wCorrect += _w;\n  }\n  return _wTotal > 0 ? Math.round((_wCorrect / _wTotal) * 100) / 100 : 0;\n})()`;
    }
    return '""';
  }

  // ── Prediction statements ────────────────────────────────────────

  _genPredictStmt(stmt) {
    const intoName = this._safeName(stmt.intoLayer);
    const dirName = this._safeName(stmt.directionsLayer);
    const lensName = this._safeName(stmt.lensesLayer);
    const qtyName = this._safeName(stmt.quantitiesLayer);
    const subject = this._escape(stmt.subject);

    this._line(`// predict: "${this._escape(stmt.subject)}" → ${this._escape(stmt.intoLayer)}`);
    this._line(`const ${intoName} = new EM.EventMathLayer('${this._escape(stmt.intoLayer)}', []);`);
    this._line(`${dirName}.events.forEach(_dir => {`);
    this.indent++;
    this._line(`${lensName}.events.forEach(_lens => {`);
    this.indent++;
    this._line(`${qtyName}.events.forEach(_qty => {`);
    this.indent++;
    this._line(`${intoName}.events.push(new EM.EventMathEvent(`);
    this.indent++;
    this._line(`'prediction_' + Date.now() + '_' + Math.random().toString(36).slice(2),`);
    this._line(`'prediction',`);
    this._line(`{`);
    this.indent++;
    this._line(`subject: '${subject}',`);
    this._line(`direction: _dir.matter ? _dir.matter.name : String(_dir.id),`);
    this._line(`lens: _lens.matter ? _lens.matter.name : String(_lens.id),`);
    this._line(`quantity: _qty.matter ? _qty.matter.name : String(_qty.id),`);
    this._line(`predicted_state: (_dir.matter ? _dir.matter.name : '') + ' change through ' + (_lens.matter ? _lens.matter.name : '') + ' lens affecting ' + (_qty.matter ? _qty.matter.name : ''),`);
    this._line(`confidence: 0.5,`);
    this._line(`resolved: false,`);
    this._line(`correct: null`);
    this.indent--;
    this._line(`}`);
    this.indent--;
    this._line(`));`);
    this.indent--;
    this._line(`});`);
    this.indent--;
    this._line(`});`);
    this.indent--;
    this._line(`});`);
    this._line('');
  }

  _genResolveStmt(stmt) {
    const layerName = this._safeName(stmt.layer);
    const outcomeVal = stmt.outcome === 'incorrect' ? 'false' : 'true';
    const cond = this._genMatterCondition(null, '_p', stmt.condition);
    this._line(`// resolve: ${this._escape(stmt.layer)}`);
    this._line(`${layerName}.events = ${layerName}.events.map(_p => {`);
    this.indent++;
    this._line(`if (${cond}) {`);
    this.indent++;
    this._line(`return new EM.EventMathEvent(_p.id, _p.cat, Object.assign({}, _p.matter, { resolved: true, correct: ${outcomeVal} }));`);
    this.indent--;
    this._line(`}`);
    this._line(`return _p;`);
    this.indent--;
    this._line(`});`);
  }

  // ── Zoom statements ──────────────────────────────────────────────

  _genZoomIn(stmt) {
    const intoVar = this._safeName(stmt.intoName);
    const fromVar = this._safeName(stmt.fromName);
    const toVar = this._safeName(stmt.toName);
    const fromNameEsc = this._escape(stmt.fromName);
    const toNameEsc = this._escape(stmt.toName);
    const intoNameEsc = this._escape(stmt.intoName);
    const gapDesc = `between ${stmt.fromName} and ${stmt.toName}`;

    this._line(`// zoom in on ${fromNameEsc} and ${toNameEsc} into ${intoNameEsc}`);

    if (stmt.fromType === 'layer') {
      // layer→layer zoom produces a new EventMathLayer
      this._line(`const ${intoVar} = new EM.EventMathLayer('${intoNameEsc}', []);`);
      this._line(`${intoVar}.zoomLevel = ((${fromVar}.zoomLevel || 1) + 1);`);
      this._line(`${intoVar}.events.push(new EM.EventMathEvent('ctrl_' + Date.now(), 'control', {`);
      this.indent++;
      this._line(`from: '${fromNameEsc}',`);
      this._line(`to: '${toNameEsc}',`);
      this._line(`zoom_level: ${intoVar}.zoomLevel,`);
      this._line(`control: true,`);
      this._line(`gap_description: '${this._escape(gapDesc)}',`);
      this._line(`from_count: ${fromVar}.events.length,`);
      this._line(`to_count: ${toVar}.events.length`);
      this.indent--;
      this._line(`}));`);
    } else {
      // event→event or timeline→timeline zoom produces a new EventMathTimeline
      this._line(`const ${intoVar} = new EM.EventMathTimeline('${intoNameEsc}');`);
      this._line(`${intoVar}.zoomLevel = ((${fromVar}.zoomLevel || 1) + 1);`);
      this._line(`const _ctrl_matter_${intoVar} = {`);
      this.indent++;
      if (stmt.fromType === 'timeline') {
        this._line(`from: ${fromVar}.name,`);
        this._line(`to: ${toVar}.name,`);
      } else {
        this._line(`from: ${fromVar}.id,`);
        this._line(`to: ${toVar}.id,`);
      }
      this._line(`zoom_level: ${intoVar}.zoomLevel,`);
      this._line(`control: true,`);
      this._line(`gap_description: '${this._escape(gapDesc)}'`);
      this.indent--;
      this._line(`};`);
      if (stmt.fromType !== 'timeline') {
        this._line(`Object.keys(${fromVar}.matter || {}).forEach(k => { _ctrl_matter_${intoVar}['from_' + k] = ${fromVar}.matter[k]; });`);
        this._line(`Object.keys(${toVar}.matter || {}).forEach(k => { _ctrl_matter_${intoVar}['to_' + k] = ${toVar}.matter[k]; });`);
      }
      this._line(`${intoVar}.append(new EM.TimelineEntry('control', new EM.EventMathEvent('ctrl_' + Date.now(), 'control', _ctrl_matter_${intoVar})));`);
    }
    this._line('');
  }

  _genZoomOut(stmt) {
    const asVar = this._safeName(stmt.asName);
    const srcVar = this._safeName(stmt.sourceName);
    const sourceNameEsc = this._escape(stmt.sourceName);
    const asNameEsc = this._escape(stmt.asName);

    this._line(`// zoom out on ${stmt.sourceType} ${sourceNameEsc} as event ${asNameEsc}`);
    if (stmt.sourceType === 'timeline') {
      this._line(`const ${asVar} = new EM.EventMathEvent(`);
      this.indent++;
      this._line(`'${asNameEsc}',`);
      this._line(`'summary',`);
      this._line(`{`);
      this.indent++;
      this._line(`source_type: 'timeline',`);
      this._line(`source_name: '${sourceNameEsc}',`);
      this._line(`zoom_level: Math.max(1, (${srcVar}.zoomLevel || 1) - 1),`);
      this._line(`entry_count: ${srcVar}.log.length,`);
      this._line(`summary: ${srcVar}.render()`);
      this.indent--;
      this._line(`}`);
      this.indent--;
      this._line(`);`);
    } else {
      // layer
      this._line(`const ${asVar} = new EM.EventMathEvent(`);
      this.indent++;
      this._line(`'${asNameEsc}',`);
      this._line(`'summary',`);
      this._line(`{`);
      this.indent++;
      this._line(`source_type: 'layer',`);
      this._line(`source_name: '${sourceNameEsc}',`);
      this._line(`zoom_level: Math.max(1, (${srcVar}.zoomLevel || 1) - 1),`);
      this._line(`event_count: ${srcVar}.events.length,`);
      this._line(`summary: ${srcVar}.render()`);
      this.indent--;
      this._line(`}`);
      this.indent--;
      this._line(`);`);
    }
    this._line('');
  }

  _genZoomOpposite(stmt) {
    const srcVar    = this._safeName(stmt.sourceName);
    const intoVar   = this._safeName(stmt.intoName);
    const srcEsc    = this._escape(stmt.sourceName);
    const intoEsc   = this._escape(stmt.intoName);

    this._line(`// zoom opposite: equal and opposite control of "${srcEsc}"`);
    this._line(`const ${intoVar} = (() => {`);
    this.indent++;
    this._line(`const __src = ${srcVar};`);
    this._line(`const __level = (__src && __src.zoomLevel) || 1;`);
    this._line(`const __opp = new EM.EventMathTimeline('${intoEsc}');`);
    this._line(`__opp.zoomLevel = __level;`);
    this._line(`__opp.opposite = true;`);
    this._line(`__opp.oppositeOf = '${srcEsc}';`);
    this._line(`__opp.polarity = -1;`);
    this._line(`const __oppMatter = {`);
    this.indent++;
    this._line(`type: 'opposite control',`);
    this._line(`opposite_of: '${srcEsc}',`);
    this._line(`zoom_level: __level,`);
    this._line(`polarity: 'negative',`);
    this._line(`description: 'equal and opposite force to ' + '${srcEsc}'`);
    this.indent--;
    this._line(`};`);
    this._line(`__opp.append(new EM.TimelineEntry('control', new EM.EventMathEvent('opp_ctrl_' + Date.now(), 'opposite control', __oppMatter)));`);
    this._line(`return __opp;`);
    this.indent--;
    this._line(`})();`);
    this._line('');
  }

  _genZoomMeta(stmt) {
    const intoVar  = this._safeName(stmt.intoName);
    const intoEsc  = this._escape(stmt.intoName);
    const subjectRefs  = stmt.subjects.map(s => this._safeName(s));
    const subjectNames = stmt.subjects.map(s => `'${this._escape(s)}'`).join(', ');

    this._line(`// zoom meta: meta-control governing [${stmt.subjects.join(', ')}]`);
    this._line(`const ${intoVar} = (() => {`);
    this.indent++;
    this._line(`const __governs = [${subjectRefs.join(', ')}];`);
    this._line(`const __maxLevel = Math.max(...__governs.map(s => (s && s.zoomLevel) || 1));`);
    this._line(`const __meta = new EM.EventMathTimeline('${intoEsc}');`);
    this._line(`__meta.zoomLevel = __maxLevel + 1;`);
    this._line(`__meta.meta = true;`);
    this._line(`__meta.governs = __governs;`);
    this._line(`__meta.governsNames = [${subjectNames}];`);
    this._line(`const __metaMatter = {`);
    this.indent++;
    this._line(`type: 'meta control',`);
    this._line(`governs_count: __governs.length,`);
    this._line(`governs: [${subjectNames}].join(', '),`);
    this._line(`zoom_level: __meta.zoomLevel,`);
    this._line(`description: 'meta-control governing the governing controls'`);
    this.indent--;
    this._line(`};`);
    this._line(`__meta.append(new EM.TimelineEntry('control', new EM.EventMathEvent('meta_ctrl_' + Date.now(), 'meta control', __metaMatter)));`);
    this._line(`return __meta;`);
    this.indent--;
    this._line(`})();`);
    this._line('');
  }

  // ── Torus statements ────────────────────────────────────────────

  _genSpinStmt(stmt) {
    const torusVar  = this._safeName(stmt.intoName);
    const sourceVar = this._safeName(stmt.sourceName);
    const intoEsc   = this._escape(stmt.intoName);
    const srcEsc    = this._escape(stmt.sourceName);

    // Accept negative dimensions (-39 to -2) as well as positive (2 to 39)
    const rawDim = typeof stmt.dimension === 'number' ? stmt.dimension : 2;
    const absD   = Math.abs(rawDim);
    const dim    = rawDim < 0 ? -(absD < 2 ? 2 : absD > 39 ? 39 : absD)
                              : (absD < 2 ? 2 : absD > 39 ? 39 : absD);
    const dimLabel = dim < 0 ? 'D-' + Math.abs(dim) : 'D+' + dim;
    this._line(`// spin ${srcEsc} into ${intoEsc}  [${dimLabel}]`);
    this._line(`const ${torusVar} = new EM.EventMathTorus('${intoEsc}');`);
    this._line(`${torusVar}.spinFrom(typeof ${sourceVar} !== 'undefined' ? ${sourceVar} : null, ${dim});`);
    this._line('');
  }

  _genVibrateStmt(stmt) {
    const torusVar = this._safeName(stmt.torusName);
    const torusEsc = this._escape(stmt.torusName);

    this._line(`// vibrate ${torusEsc} across ${stmt.rings} rings`);
    this._line(`${torusVar}.expand(${stmt.rings});`);
    this._line('');
  }

  _genCycleStmt(stmt) {
    const torusVar = this._safeName(stmt.torusName);
    const torusEsc = this._escape(stmt.torusName);

    this._line(`// cycle ${torusEsc} — mark the completion event`);
    this._line(`${torusVar}.complete();`);
    this._line('');
  }

  _genResonateStmt(stmt) {
    const firstVar   = this._safeName(stmt.firstName);
    const secondVar  = this._safeName(stmt.secondName);
    const firstEsc   = this._escape(stmt.firstName);
    const secondEsc  = this._escape(stmt.secondName);

    this._line(`// resonate ${firstEsc} and ${secondEsc}`);
    this._line(`if (${firstVar} && typeof ${firstVar}.addResonance === 'function') ${firstVar}.addResonance('${secondEsc}');`);
    this._line(`if (${secondVar} && typeof ${secondVar}.addResonance === 'function') ${secondVar}.addResonance('${firstEsc}');`);
    this._line('');
  }

  // ── v1.6 Reasoning statements ────────────────────────────────────

  // weight <name> at <N>  — store probability weight in registry
  _genWeightStmt(stmt) {
    const key = this._safeName(stmt.targetName);
    const esc = this._escape(stmt.targetName);
    this._line(`// weight: ${esc} = ${stmt.value}`);
    this._line(`__weights['${key}'] = ${stmt.value};`);
    this._line('');
  }

  // explain <observations> from <candidates> into <result>
  // Abductive: find the candidate from <candidates> that best explains
  // the pattern of correct predictions in <observations>.
  _genExplainStmt(stmt) {
    const obsVar  = this._safeName(stmt.observations);
    const canVar  = this._safeName(stmt.candidates);
    const intoVar = this._safeName(stmt.intoName);
    const obsEsc  = this._escape(stmt.observations);
    const canEsc  = this._escape(stmt.candidates);
    const intoEsc = this._escape(stmt.intoName);

    this._line(`// explain ${obsEsc} from ${canEsc} into ${intoEsc}`);
    this._line(`const ${intoVar} = (() => {`);
    this.indent++;
    // Collect correct observations — handle both layer.events and raw arrays
    this._line(`const __obs = (Array.isArray(${obsVar}) ? ${obsVar} : (${obsVar}.events || []));`);
    this._line(`const __isTruthy = v => v === true || v === 'true';`);
    this._line(`const __correct = __obs.filter(_p => _p.matter && __isTruthy(_p.matter.resolved) && __isTruthy(_p.matter.correct));`);
    this._line(`const __candidates = (Array.isArray(${canVar}) ? ${canVar} : (${canVar}.events || []));`);
    this._line(`let __bestScore = -1, __bestEvt = null, __bestReason = '';`);
    this._line(`for (const __c of __candidates) {`);
    this.indent++;
    this._line(`let __score = 0;`);
    this._line(`const __cMatter = __c.matter || {};`);
    this._line(`for (const __p of __correct) {`);
    this.indent++;
    this._line(`const __pMatter = __p.matter || {};`);
    // Weight-adjusted scoring: each field match scores weight of that field
    this._line(`for (const __k of Object.keys(__cMatter)) {`);
    this.indent++;
    this._line(`if (__pMatter[__k] !== undefined && __pMatter[__k] === __cMatter[__k]) {`);
    this.indent++;
    this._line(`__score += (__weights[String(__cMatter[__k])] || __weights[__k] || 1);`);
    this.indent--;
    this._line(`}`);
    this.indent--;
    this._line(`}`);
    this.indent--;
    this._line(`}`);
    this._line(`if (__score > __bestScore) {`);
    this.indent++;
    this._line(`__bestScore = __score;`);
    this._line(`__bestEvt = __c;`);
    this._line(`__bestReason = 'matched ' + Object.keys(__cMatter).filter(k => __correct.some(p => (p.matter||{})[k] === __cMatter[k])).join(', ');`);
    this.indent--;
    this._line(`}`);
    this.indent--;
    this._line(`}`);
    // Wrap best result as an event with explanation metadata
    this._line(`if (!__bestEvt) return new EM.EventMathEvent('no_explanation', 'explanation', { score: 0, reason: 'no candidates matched' });`);
    this._line(`const __expMatter = Object.assign({}, __bestEvt.matter, {`);
    this.indent++;
    this._line(`explanation_score: Math.round(__bestScore * 100) / 100,`);
    this._line(`explanation_of: '${obsEsc}',`);
    this._line(`matched_fields: __bestReason,`);
    this._line(`abductive: true`);
    this.indent--;
    this._line(`});`);
    this._line(`return new EM.EventMathEvent(__bestEvt.id + '_explanation', 'explanation', __expMatter);`);
    this.indent--;
    this._line(`})();`);
    this._line('');
  }

  // analogy <X> and <Y> into <Z>
  // Analogical: compute structural similarity between X and Y (0-1 score).
  // Compares: matter field overlap (Jaccard), zoom level match, governance role match.
  _genAnalogyStmt(stmt) {
    const firstVar  = this._safeName(stmt.firstName);
    const secondVar = this._safeName(stmt.secondName);
    const intoVar   = this._safeName(stmt.intoName);
    const firstEsc  = this._escape(stmt.firstName);
    const secondEsc = this._escape(stmt.secondName);
    const intoEsc   = this._escape(stmt.intoName);

    this._line(`// analogy ${firstEsc} and ${secondEsc} into ${intoEsc}`);
    this._line(`const ${intoVar} = (() => {`);
    this.indent++;
    // Extract matter from event, timeline control entry, or raw object
    this._line(`function __getMatter(x) {`);
    this.indent++;
    this._line(`if (!x) return {};`);
    this._line(`if (x.matter) return x.matter;`);
    this._line(`if (x.log && x.log[0] && x.log[0].data) return x.log[0].data.matter || {};`);
    this._line(`return {};`);
    this.indent--;
    this._line(`}`);
    this._line(`const __aM = __getMatter(${firstVar});`);
    this._line(`const __bM = __getMatter(${secondVar});`);
    this._line(`const __aKeys = new Set(Object.keys(__aM));`);
    this._line(`const __bKeys = new Set(Object.keys(__bM));`);
    // Jaccard similarity on matter fields with matching values
    this._line(`const __intersection = [...__aKeys].filter(k => __bKeys.has(k) && __aM[k] === __bM[k]).length;`);
    this._line(`const __union = new Set([...__aKeys, ...__bKeys]).size;`);
    this._line(`const __matterSim = __union > 0 ? __intersection / __union : 1;`);
    // Structural similarity: zoom level, opposite, meta, rings
    this._line(`let __sScore = 0, __sTotal = 0;`);
    this._line(`const __a = ${firstVar}, __b = ${secondVar};`);
    this._line(`if (__a.zoomLevel !== undefined && __b.zoomLevel !== undefined) { __sTotal++; if (__a.zoomLevel === __b.zoomLevel) __sScore++; }`);
    this._line(`if (__a.opposite !== undefined || __b.opposite !== undefined) { __sTotal++; if (__a.opposite === __b.opposite) __sScore++; }`);
    this._line(`if (__a.meta !== undefined || __b.meta !== undefined) { __sTotal++; if (__a.meta === __b.meta) __sScore++; }`);
    this._line(`if (__a.rings !== undefined || __b.rings !== undefined) { __sTotal++; if ((__a.rings||[]).length === (__b.rings||[]).length) __sScore++; }`);
    this._line(`const __structSim = __sTotal > 0 ? __sScore / __sTotal : 1;`);
    this._line(`return Math.round((__matterSim * 0.6 + __structSim * 0.4) * 100) / 100;`);
    this.indent--;
    this._line(`})();`);
    this._line('');
  }

  // ── v1.7 Multi-dimensional landscape ────────────────────────────

  // landscape from T1 and T2 and ... into L
  _genLandscapeStmt(stmt) {
    const intoVar = this._safeName(stmt.intoName);
    const intoEsc = this._escape(stmt.intoName);
    this._line(`// landscape: ${intoEsc}`);
    this._line(`${intoVar} = new EM.EventMathLandscape('${intoEsc}');`);
    for (const src of (stmt.sources || [])) {
      const srcVar = this._safeName(src);
      const srcEsc = this._escape(src);
      this._line(`if (typeof ${srcVar} !== 'undefined' && ${srcVar} && typeof ${srcVar}.dimension !== 'undefined') { ${intoVar}.addTorus(${srcVar}); }`);
    }
    this._line('');
  }

  // forecast from L into F
  _genForecastStmt(stmt) {
    const landVar = this._safeName(stmt.landscapeName);
    const intoVar = this._safeName(stmt.intoName);
    const intoEsc = this._escape(stmt.intoName);
    this._line(`// forecast from ${this._escape(stmt.landscapeName)} into ${intoEsc}`);
    this._line(`${intoVar} = ${landVar}.forecast();`);
    this._line('');
  }

  // bound <firstName> and <secondName> into <intoName>
  // Bridges negative-D and positive-D toruses into the full complex axis structure:
  //   bridge (i), anti-bridge (-i), meta (ℝ), anti-meta (-ℝ), grand (ℂ)
  _genBoundStmt(stmt) {
    const firstVar  = this._safeName(stmt.firstName);
    const secondVar = this._safeName(stmt.secondName);
    const intoVar   = this._safeName(stmt.intoName);
    const firstEsc  = this._escape(stmt.firstName);
    const secondEsc = this._escape(stmt.secondName);
    const intoEsc   = this._escape(stmt.intoName);
    this._line(`// bound "${firstEsc}" and "${secondEsc}" → "${intoEsc}"`);
    this._line(`// bridge=i  anti-bridge=-i  meta=R  anti-meta=-R  grand=C`);
    this._line(`${intoVar} = new EM.EventMathAxis('${intoEsc}', ${firstVar}, ${secondVar});`);
    this._line('');
  }

  /**
   * Generate a JS boolean expression checking _p.matter fields from a condition node or string.
   * condStr: raw "field is value and field2 is value2" string  (for accuracy_of)
   * condNode: parsed Condition/CompoundCondition AST node      (for resolve)
   */
  _genMatterCondition(condStr, varName, condNode) {
    const v = varName || '_p';
    if (condNode) {
      return this._genMatterConditionNode(condNode, v);
    }
    if (!condStr) return 'true';
    // Parse simple "field is value [and field is value ...]" string
    const parts = condStr.split(' and ');
    const exprs = parts.map(part => {
      const isIdx = part.indexOf(' is ');
      if (isIdx >= 0) {
        const field = part.slice(0, isIdx).trim();
        const value = part.slice(isIdx + 4).trim();
        const safeField = this._safeName(field);
        let jsVal;
        if (/^\d+(\.\d+)?$/.test(value)) jsVal = value;
        else if (value === 'true' || value === 'false') jsVal = value;
        else jsVal = `"${this._escape(value)}"`;
        return `${v}.matter.${safeField} === ${jsVal}`;
      }
      return 'true';
    });
    return exprs.join(' && ');
  }

  _genMatterConditionNode(cond, v) {
    if (!cond) return 'true';
    if (cond.type === 'CompoundCondition') {
      const left = this._genMatterConditionNode(cond.left, v);
      const right = this._genMatterConditionNode(cond.right, v);
      const op = cond.op === 'and' ? '&&' : '||';
      return `(${left}) ${op} (${right})`;
    }
    // Simple condition
    const field = this._safeName(cond.left);
    const rightVal = cond.right || '';
    let jsVal;
    if (rightVal === 'true') jsVal = 'true';
    else if (rightVal === 'false') jsVal = 'false';
    else if (/^\d+(\.\d+)?$/.test(rightVal)) jsVal = rightVal;
    else jsVal = `"${this._escape(rightVal)}"`;
    return `${v}.matter.${field} === ${jsVal}`;
  }

  // ── Layer operations (sort/filter/find/count) ────────────────────

  /**
   * Parse a simple "field is value" condition string for layer operations.
   * Returns a JS expression string using evt.matter.<field>.
   */
  _genLayerCondition(condStr) {
    if (!condStr) return 'true';
    // Simple "field is value" pattern
    const isIdx = condStr.indexOf(' is ');
    if (isIdx >= 0) {
      const field = condStr.slice(0, isIdx).trim();
      const value = condStr.slice(isIdx + 4).trim();
      const safeField = this._safeName(field);
      // Value: number, bool, or string literal
      let jsVal;
      if (/^\d+(\.\d+)?$/.test(value)) jsVal = value;
      else if (value === 'true' || value === 'false') jsVal = value;
      else jsVal = `"${this._escape(value)}"`;
      return `evt.matter.${safeField} === ${jsVal}`;
    }
    return 'true';
  }

  _genSortLayer(stmt) {
    const varName = this._safeName(stmt.name);
    const field = this._safeName(stmt.field);
    if (stmt.direction === 'descending') {
      this._line(`${varName}.events.sort((a, b) =>`);
      this._line(`  String(b.matter.${field} || '').localeCompare(String(a.matter.${field} || '')));`);
    } else {
      this._line(`${varName}.events.sort((a, b) =>`);
      this._line(`  String(a.matter.${field} || '').localeCompare(String(b.matter.${field} || '')));`);
    }
  }

  _genFilterLayer(stmt) {
    const varName = this._safeName(stmt.name);
    const intoName = this._safeName(stmt.into);
    const cond = this._genLayerCondition(stmt.condition);
    this._line(`const ${intoName} = new EM.EventMathLayer("${this._escape(stmt.into)}",`);
    this._line(`  ${varName}.events.filter(evt => ${cond}));`);
  }

  _genFindInLayer(stmt) {
    const varName = this._safeName(stmt.name);
    const intoName = this._safeName(stmt.into);
    const cond = this._genLayerCondition(stmt.condition);
    this._line(`let ${intoName} = ${varName}.events.find(evt => ${cond}) || null;`);
  }

  _genCountInLayer(stmt) {
    const varName = this._safeName(stmt.name);
    const intoName = this._safeName(stmt.into);
    const cond = this._genLayerCondition(stmt.condition);
    this._line(`let ${intoName} = ${varName}.events.filter(evt => ${cond}).length;`);
  }

  // ── Arithmetic expressions ───────────────────────────────────────

  _genExpr(node) {
    if (!node) return '0';
    if (node.kind === 'expr') {
      const ops = { plus: '+', minus: '-', times: '*', 'divided by': '/', 'take away': '-' };
      const jsOp = ops[node.op] || '+';
      const left  = node.left.kind  === 'expr' ? `(${this._genExpr(node.left)})`  : this._exprOperand(node.left);
      const right = node.right.kind === 'expr' ? `(${this._genExpr(node.right)})` : this._exprOperand(node.right);
      return `${left} ${jsOp} ${right}`;
    }
    return this._exprOperand(node);
  }

  _exprOperand(operand) {
    if (!operand) return '0';
    if (operand.kind === 'number') return operand.value;
    if (operand.kind === 'name') {
      // past/present/future are the numberless numbers: -1, 0, 1
      const n = operand.value;
      if (n === 'past')    return '-1';
      if (n === 'present') return '0';
      if (n === 'future')  return '1';
      return this._safeRef(n);
    }
    return `"${this._escape(operand.value || '')}"`;
  }

  // ── Run ─────────────────────────────────────────────────────────

  _genRun(stmt) {
    if (!stmt.target) {
      this._line(`console.log('');`);
      return;
    }
    const words = stmt.target.split(' ');
    const kind = words[0];
    const name = words.slice(1).join(' ') || words[0];

    if (kind === 'event') {
      this._line(`console.log(${this._safeName(name)}.render());`);
    } else if (kind === 'layer') {
      this._line(`console.log(${this._safeName(name)}.render());`);
    } else if (kind === 'timeline') {
      this._line(`console.log(${this._safeName(name)}.render());`);
    } else {
      // Timeline section: "story present" or "story past"
      const parts = stmt.target.split(' ');
      const section = parts[parts.length - 1];
      const timelineName = parts.slice(0, parts.length - 1).join(' ');
      if (['past', 'present', 'future'].includes(section)) {
        this._line(`console.log(${this._safeName(timelineName)}.renderSection('${section}'));`);
      } else {
        this._line(`console.log(${this._safeName(stmt.target)}.render());`);
      }
    }
  }

  _genShow(stmt) {
    if (!stmt.target) {
      this._line(`console.log('');`);
      return;
    }
    const label = stmt.target;
    const safeName = this._safeName(label);
    this._line(`{ const __sv = ${safeName}; if (__sv !== null && __sv !== undefined && typeof __sv.render === 'function') { console.log(__sv.render()); } else { console.log('${label.replace(/'/g, "\\'")}:', __sv); } }`);
  }

  // ── Conditionals ────────────────────────────────────────────────

  _genWhen(stmt) {
    if (!stmt.condition) {
      this._line(`// (when with no condition)`);
      return;
    }
    const cond = this._genCondition(stmt.condition);
    this._line(`if (${cond}) {`);
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;

    if (stmt.otherwise && stmt.otherwise.length > 0) {
      this._line(`} else {`);
      this.indent++;
      for (const bodyStmt of stmt.otherwise) {
        this._genStatement(bodyStmt, this._inAction);
      }
      this.indent--;
    }

    this._line(`}`);
  }

  _genCondition(cond) {
    if (!cond) return 'true';

    // Compound condition (and/or)
    if (cond.type === 'CompoundCondition') {
      const left = this._genCondition(cond.left);
      const right = this._genCondition(cond.right);
      const op = cond.op === 'and' ? '&&' : '||';
      return `(${left}) ${op} (${right})`;
    }

    // Simple condition (Condition node)
    const left = this._walkRef(cond.left);
    const rightVal = cond.right || '';
    let right;
    if (rightVal === 'true') right = 'true';
    else if (rightVal === 'false') right = 'false';
    else if (/^\d+(\.\d+)?$/.test(rightVal)) right = rightVal;
    else right = `"${this._escape(rightVal)}"`;

    const ops = {
      'is':               `${left} === ${right}`,
      'is not':           `${left} !== ${right}`,
      'is greater than':  `${left} > ${this._numRef(cond.right)}`,
      'is less than':     `${left} < ${this._numRef(cond.right)}`,
      'is at least':      `${left} >= ${this._numRef(cond.right)}`,
      'is at most':       `${left} <= ${this._numRef(cond.right)}`,
      'is starts with':   `String(${left}).startsWith(${right})`,
      'is ends with':     `String(${left}).endsWith(${right})`,
      'is contains':      `String(${left}).includes(${right})`,
      // Legacy operator names (without 'is' prefix) for backward compatibility
      'greater than':     `${left} > ${this._numRef(cond.right)}`,
      'less than':        `${left} < ${this._numRef(cond.right)}`,
      'at least':         `${left} >= ${this._numRef(cond.right)}`,
      'at most':          `${left} <= ${this._numRef(cond.right)}`,
    };

    return ops[cond.op] || `${left} === ${right}`;
  }

  // For numeric comparisons: emit variable reference or number, not string
  _numRef(val) {
    if (!val) return '0';
    if (/^\d+(\.\d+)?$/.test(val)) return val;
    return this._safeRef(val);
  }

  /**
   * Resolve a name reference, supporting walk variable property access.
   * "current task status" → "current_task.status" when walkVar = "current task"
   */
  _walkRef(name) {
    if (!this._walkVar || !name) return this._safeRef(name);
    const walkVarSafe = this._safeName(this._walkVar);
    if (name === this._walkVar) return walkVarSafe;
    const prefix = this._walkVar;
    if (name.startsWith(prefix + ' ')) {
      const rest = name.slice(prefix.length).trim();
      if (rest) {
        return `${walkVarSafe}.matter.${this._safeName(rest)}`;
      }
      return walkVarSafe;
    }
    return this._safeRef(name);
  }

  // ── Split ──────────────────────────────────────────────────────

  _genSplit(stmt) {
    const target = this._safeRef(stmt.target);
    this._line(`// split ${target}`);
    this._line(`switch (${target}) {`);
    this.indent++;

    for (const path of (stmt.paths || [])) {
      this._line(`case "${this._escape(path.name)}":`);
      this.indent++;
      for (const bodyStmt of (path.body || [])) {
        this._genStatement(bodyStmt, this._inAction);
      }
      this._line(`break;`);
      this.indent--;
    }

    this.indent--;
    this._line(`}`);
  }

  // ── Loops ──────────────────────────────────────────────────────

  _genAgainCount(stmt) {
    const count = stmt.count || 0;
    this._line(`for (let __i = 0; __i < ${count}; __i++) {`);
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;
    this._line(`}`);
  }

  _genAgainUntil(stmt) {
    if (!stmt.condition) {
      this._line(`while (true) {`);
    } else {
      const cond = this._genCondition(stmt.condition);
      // Invert: "again until X is true" = "while (!X)"
      this._line(`while (!(${cond})) {`);
    }
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;
    this._line(`}`);
  }

  _genWalk(stmt) {
    const layer = this._safeName(stmt.layer);
    const variable = this._safeName(stmt.variable);
    this._walkVar = stmt.variable; // Track for property access in conditions
    this._line(`for (const ${variable} of ${layer}.events) {`);
    this.indent++;
    for (const bodyStmt of (stmt.body || [])) {
      this._genStatement(bodyStmt, this._inAction);
    }
    this.indent--;
    this._line(`}`);
    this._walkVar = null;
  }

  // ── Stop ────────────────────────────────────────────────────────

  _genStop(stmt) {
    // Emit return (works in both functions and top-level scripts)
    this._line(`return;`);
  }

  // ── Action calls ────────────────────────────────────────────────

  _genActionCall(stmt, inAction) {
    const fnName = this._camelName(stmt.name);
    const doorInputs = this._actionDoorInputs[stmt.name] || [];
    const argMap = {}; // key -> value
    for (const arg of (stmt.args || [])) {
      argMap[arg.key] = arg.value;
    }
    // Emit args in door input order, matching by key
    const args = doorInputs.map(key => {
      const val = argMap[key];
      if (val !== undefined) {
        return `"${this._escape(val)}"`;
      }
      return 'undefined';
    });
    this._line(`${fnName}(${args.join(', ')});`);
  }

  // ── Time travel ────────────────────────────────────────────────

  _genRewind(stmt) {
    const target = this._safeName(stmt.target);
    if (stmt.mode === 'by') {
      this._line(`${target}.rewind(${stmt.count || 1});`);
    } else if (stmt.mode === 'to') {
      this._line(`${target}.rewindTo("${this._escape(stmt.destination)}");`);
    }
  }

  _genForward(stmt) {
    const target = this._safeName(stmt.target);
    if (stmt.mode === 'by') {
      this._line(`${target}.forward(${stmt.count || 1});`);
    } else if (stmt.mode === 'to') {
      this._line(`${target}.forwardTo("${this._escape(stmt.destination)}");`);
    }
  }

  // ── Layer operations ──────────────────────────────────────────

  _genAddEvent(stmt) {
    const eventName = this._safeName(stmt.eventName);
    const layerName = this._safeName(stmt.layerName);
    if (layerName) {
      this._line(`${layerName}.events.push(${eventName});`);
    }
  }

  _genAddLayer(stmt) {
    this._line(`// add layer: ${stmt.layerName}`);
  }

  _genRemoveLayer(stmt) {
    this._line(`// remove layer: ${stmt.name}`);
  }

  _genRemoveEvent(stmt) {
    this._line(`// remove event: ${stmt.name}`);
  }

  _genMerge(stmt) {
    this._line(`// merge ${stmt.source} into ${stmt.target}`);
  }

  // ── Broken Event ───────────────────────────────────────────────

  _genBrokenEvent(stmt) {
    const varName = this._safeName(stmt.name);
    this._line(`// broken event: "${this._escape(stmt.name)}"`);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${this._escape(stmt.name)}",`);
    this._line(`"broken",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line(`console.error(${varName}.render());`);
    this._line('');
  }

  // ── Check assertion ────────────────────────────────────────────

  _genCheck(stmt) {
    if (!stmt.condition) return;
    const cond = this._genCondition(stmt.condition);
    const desc = stmt.condition.type === 'CompoundCondition'
      ? `compound condition`
      : `${stmt.condition.left} ${stmt.condition.op} ${stmt.condition.right}`;
    this._line(`if (!(${cond})) {`);
    this.indent++;
    this._line(`console.error(new EM.EventMathEvent("check failed", "broken", {`);
    this.indent++;
    this._line(`condition: "${this._escape(desc)}",`);
    this._line(`hint: "This condition was expected to be true.",`);
    this.indent--;
    this._line(`}).render());`);
    this.indent--;
    this._line(`}`);
  }

  // ── Overlap & Note ─────────────────────────────────────────────

  /**
   * Recursively checks whether any node in the AST is an Overlap.
   */
  _detectOverlap(statements) {
    if (!statements) return false;
    for (const stmt of statements) {
      if (!stmt) continue;
      if (stmt.type === 'Overlap') return true;
      // Check nested bodies
      if (stmt.body && this._detectOverlap(stmt.body)) return true;
      if (stmt.otherwise && this._detectOverlap(stmt.otherwise)) return true;
      if (stmt.tracks) {
        for (const track of stmt.tracks) {
          if (this._detectOverlap(track)) return true;
        }
      }
      // Check path bodies in split
      if (stmt.paths) {
        for (const path of stmt.paths) {
          if (path.body && this._detectOverlap(path.body)) return true;
        }
      }
    }
    return false;
  }

  _genOverlap(stmt) {
    this._line('// overlap: run these tracks at the same time');
    this._line('await Promise.all([');
    this.indent++;
    for (const track of (stmt.tracks || [])) {
      this._line('(async () => {');
      this.indent++;
      for (const s of track) this._genStatement(s, this._inAction);
      this.indent--;
      this._line('})(),');
    }
    this.indent--;
    this._line(']);');
  }

  _genNote(stmt) {
    this._line(`// note: ${stmt.text}`);
  }

  // ── Use / Import ───────────────────────────────────────────────

  _genUse(stmt) {
    if (!stmt.from) return;
    // Convert .em filename to .em.js
    const compiledFile = stmt.from.replace(/\.em$/, '.em.js');
    const safeName = this._safeName(stmt.name);
    const camelName = this._camelName(stmt.name);
    const names = safeName === camelName ? safeName : `${safeName}, ${camelName}`;
    this._line(`// use ${stmt.name} from ${stmt.from}`);
    this._line(`const { ${names} } = require('./${compiledFile}');`);
  }

  // ── Helpers ─────────────────────────────────────────────────────

  _safeName(name) {
    if (!name) return '__empty';
    // Convert "User can log in" → "User_can_log_in"
    // Prefix with __ if it starts with a digit
    let s = name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_$]/g, '');
    if (/^\d/.test(s)) s = '_' + s;
    if (/^[a-zA-Z_$]/.test(s)) return s;
    return '_' + s;
  }

  _safeKey(key) {
    if (!key) return '"_empty"';
    // Object keys that aren't valid JS identifiers need quoting
    const idRegex = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
    if (idRegex.test(key)) return key;
    return `"${key}"`;
  }

  _safeRef(name) {
    if (!name) return 'undefined';
    // Check if it's an imported name — emit safeName, let runtime handle
    if (this._importedNames && this._importedNames.has(name)) {
      return this._safeName(name);
    }
    const safe = this._safeName(name);
    if (safe === 'true' || safe === 'false') return safe;
    if (safe === 'undefined') return 'undefined';
    return safe;
  }

  _camelName(name) {
    // "make requirement" → "makeRequirement"
    if (!name) return 'unnamed';
    return name.split(/\s+/).map((w, i) =>
      i === 0 ? w.replace(/[^a-zA-Z0-9_$]/g, '') :
        w.charAt(0).toUpperCase() + w.slice(1).replace(/[^a-zA-Z0-9_$]/g, '')
    ).join('');
  }

  _escape(str) {
    if (typeof str !== 'string') return String(str);
    return str.replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');
  }

  // ── v2.0 code generators ────────────────────────────────────────

  _genActorStmt(stmt) {
    const varName = this._safeName(stmt.name);
    const nameEsc = this._escape(stmt.name);
    this._line(`// Actor: "${nameEsc}"`);
    this._line(`const ${varName} = new EM.EventMathActor(`);
    this.indent++;
    this._line(`"${nameEsc}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line('');
  }

  _genChainStmt(stmt) {
    const varName = this._safeName(stmt.name);
    const nameEsc = this._escape(stmt.name);
    this._line(`// Chain: "${nameEsc}"`);
    this._line(`${varName} = new EM.EventMathChain('${nameEsc}');`);
    for (const link of (stmt.links || [])) {
      const fromEsc = this._escape(link.from);
      const toEsc   = this._escape(link.to);
      const valArg  = (link.value !== null && link.value !== undefined && !isNaN(link.value))
        ? `, ${link.value}` : '';
      this._line(`${varName}.addLink('${fromEsc}', '${toEsc}'${valArg});`);
    }
    this._line('');
  }

  _genEventLikeStmt(stmt) {
    // desire blocks get EventMathDesire — all other EventLike stmts get EventMathEvent
    if (stmt.keyword === 'desire') return this._genDesireStmt(stmt);

    const varName  = this._safeName(stmt.name);
    const nameEsc  = this._escape(stmt.name);
    const catEsc   = this._escape(stmt.category || stmt.keyword || 'event');
    this._line(`// ${stmt.keyword}: "${nameEsc}"`);
    this._line(`const ${varName} = new EM.EventMathEvent(`);
    this.indent++;
    this._line(`"${nameEsc}",`);
    this._line(`"${catEsc}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line('');
  }

  _genDesireStmt(stmt) {
    const varName = this._safeName(stmt.name);
    const nameEsc = this._escape(stmt.name);
    this._line(`// desire: "${nameEsc}"`);
    this._line(`const ${varName} = new EM.EventMathDesire(`);
    this.indent++;
    this._line(`"${nameEsc}",`);
    if (stmt.matter && stmt.matter.fields.length > 0) {
      this._line(`{`);
      this.indent++;
      for (const field of stmt.matter.fields) {
        if (field.kind === 'literal') {
          this._line(`${this._safeKey(field.key)}: "${this._escape(field.value)}",`);
        } else {
          this._line(`${this._safeKey(field.key)}: ${this._safeRef(field.value)},`);
        }
      }
      this.indent--;
      this._line(`}`);
    } else {
      this._line(`{}`);
    }
    this.indent--;
    this._line(`);`);
    this._line('');
  }

  _genSatisfyStmt(stmt) {
    const desireVar = this._safeName(stmt.desireName);
    const chainVar  = this._safeName(stmt.chainName);
    const intoVar   = this._safeName(stmt.intoName);
    const intoEsc   = this._escape(stmt.intoName);
    this._line(`// satisfy: "${this._escape(stmt.desireName)}" against "${this._escape(stmt.chainName)}"`);
    this._line(`${intoVar} = new EM.EventMathSatisfactionEngine('${intoEsc}', [${desireVar}], ${chainVar}, __assumptions);`);
    this._line('');
  }

  _genEvaluateStmt(stmt) {
    const desireVarList = (stmt.desireNames || []).map(n => this._safeName(n)).join(', ');
    const chainVar      = this._safeName(stmt.chainName);
    const intoVar       = this._safeName(stmt.intoName);
    const intoEsc       = this._escape(stmt.intoName);
    const desireLabel   = (stmt.desireNames || []).map(n => `"${this._escape(n)}"`).join(', ');
    this._line(`// evaluate: [${desireLabel}] against "${this._escape(stmt.chainName)}"`);
    this._line(`${intoVar} = new EM.EventMathSatisfactionEngine('${intoEsc}', [${desireVarList}], ${chainVar}, __assumptions);`);
    this._line('');
  }

  _genAsymmetryStmt(stmt) {
    const firstVar  = this._safeName(stmt.firstName);
    const secondVar = this._safeName(stmt.secondName);
    const intoVar   = this._safeName(stmt.intoName);
    const intoEsc   = this._escape(stmt.intoName);
    this._line(`// asymmetry: power gap between "${this._escape(stmt.firstName)}" and "${this._escape(stmt.secondName)}"`);
    this._line(`${intoVar} = new EM.EventMathPowerGap('${intoEsc}', ${firstVar}, ${secondVar});`);
    this._line('');
  }

  _genRootOfStmt(stmt) {
    const intoVar  = this._safeName(stmt.intoName);
    const intoEsc  = this._escape(stmt.intoName);
    const stateEsc = this._escape(stmt.stateName);
    this._line(`// root of: trace "${stateEsc}" backward through chain`);
    if (stmt.chainName) {
      const chainVar = this._safeName(stmt.chainName);
      this._line(`${intoVar} = ${chainVar}.trace('${stateEsc}');`);
    } else {
      // No chain specified — emit a note; trace requires a chain at runtime
      this._line(`${intoVar} = new EM.EventMathRootTrace(null, '${stateEsc}');`);
    }
    this._line('');
  }

  _genInvertStmt(stmt) {
    const srcVar  = this._safeName(stmt.sourceName);
    const intoVar = this._safeName(stmt.intoName);
    const intoEsc = this._escape(stmt.intoName);
    this._line(`// invert: reverse chain "${this._escape(stmt.sourceName)}"`);
    this._line(`${intoVar} = (${srcVar} && typeof ${srcVar}.invert === 'function') ? ${srcVar}.invert() : new EM.EventMathChain('${intoEsc}');`);
    this._line('');
  }

  _genAssumeStmt(stmt) {
    const nameEsc  = this._escape(stmt.name  || stmt.text || '');
    const valueEsc = this._escape(stmt.value || '');
    const varName  = this._safeName(stmt.name || stmt.text || '');
    this._line(`// assume: "${nameEsc}" is "${valueEsc}"`);
    this._line(`${varName} = new EM.EventMathAssumption('${nameEsc}', '${valueEsc}');`);
    this._line(`__assumptions.push(${varName});`);
    this._line('');
  }

  _genDetectFallaciesStmt(stmt) {
    const chainVar = this._safeName(stmt.chainName);
    const intoVar  = this._safeName(stmt.intoName);
    const intoEsc  = this._escape(stmt.intoName);
    this._line(`// detect fallacies in "${this._escape(stmt.chainName)}"`);
    this._line(`${intoVar} = new EM.EventMathFallacyDetector(${chainVar});`);
    this._line('');
  }

  _genFractalStmt(stmt) {
    const firstVar  = this._safeName(stmt.firstName);
    const secondVar = this._safeName(stmt.secondName);
    const intoVar   = this._safeName(stmt.intoName);
    const intoEsc   = this._escape(stmt.intoName);
    this._line(`// fractal axis: "${this._escape(stmt.firstName)}" and "${this._escape(stmt.secondName)}" → "${intoEsc}"`);
    this._line(`${intoVar} = new EM.EventMathFractalAxis('${intoEsc}', ${firstVar}, ${secondVar});`);
    this._line('');
  }

  _genDimensionalStmt(stmt) {
    const desireVarList = (stmt.desireNames || []).map(n => this._safeName(n)).join(', ');
    const chainVar      = this._safeName(stmt.chainName);
    const fractalVar    = this._safeName(stmt.fractalName);
    const intoVar       = this._safeName(stmt.intoName);
    const intoEsc       = this._escape(stmt.intoName);
    const desireLabel   = (stmt.desireNames || []).map(n => `"${this._escape(n)}"`).join(', ');
    this._line(`// dimensional: [${desireLabel}] against "${this._escape(stmt.chainName)}" across fractal "${this._escape(stmt.fractalName)}"`);
    this._line(`${intoVar} = new EM.EventMathDimensionalReport('${intoEsc}', [${desireVarList}], ${chainVar}, ${fractalVar}, __assumptions);`);
    this._line('');
  }
}

module.exports = { EventMathCodeGen };
